### ISSUE TITLE
ddl check mode

### ISSUE THREAD

**Issue by RekGRpth** [okbob/plpgsql_check#100]
How about ddl check mode? I.e. at create or replace function?

**Comment by okbob** [comment]
What do you think?

**Comment by RekGRpth** [comment]
I want to check function at create or replace (instead start).

**Comment by okbob** [comment]
```
CREATE OR REPLACE FUNCTION public.check_on_create_fx_trg_func()
 RETURNS event_trigger
 LANGUAGE plpgsql
AS $function$
declare
  r record;
  rc int;
begin
  for r in select * from pg_event_trigger_ddl_commands()
  loop
    if r.classid = 'pg_proc'::regclass and
       exists(select * from pg_proc
                where oid = r.objid
                  and prolang = (select oid from pg_language where lanname = 'plpgsql'))
    then
      perform * from plpgsql_check_function_tb(r.objid, fatal_errors=>false);
      get diagnostics rc = row_count;
      if (rc > 0) then
        raise warning 'there are some errors or warnings (%) detected by plpgsql_check on function %', rc, r.objid::regprocedure;
      end if;
    end if;
  end loop;
end;
$function$
;

create event trigger plpgsql_check_evtr on ddl_command_end execute function check_on_create_fx_trg_func();
```

**Comment by RekGRpth** [comment]
If is this possible to do via shared_preload_libraries for every databases without creating extension in it?

**Comment by okbob** [comment]
you can install this to template1, and then every new database will have this functionality.

There is an possibility to use executor hooks, and then it can be started by implicitly via shared_preload_libraries. But this is relatively aggressive technique. Why you need it?

**Comment by RekGRpth** [comment]
> There is an possibility to use executor hooks, and then it can be started by implicitly via shared_preload_libraries. But this is relatively aggressive technique. Why you need it?

It is simpler to use for many existing databases.

**Comment by okbob** [comment]
po 6. 12. 2021 v 7:20 odesílatel RekGRpth ***@***.***> napsal:

> There is an possibility to use executor hooks, and then it can be started
> by implicitly via shared_preload_libraries. But this is relatively
> aggressive technique. Why you need it?
>
> It is simpler to use for many existing databases.
>
This mode is very limited - there can be a lot of false alarms, and you
cannot easily customize parameters for plpgsql_check. So I am not in a
hurry to implement it as a base feature.

If somebody wants it, then he can use event triggers - it is safe, and
whoever creates it, then he knows what he does.

For any case plpgsql_check needs to be installed in any database, and then
it is not too much more work to install this event trigger.

**Comment by RekGRpth** [comment]
> CREATE OR REPLACE FUNCTION public.check_on_create_fx_trg_func()
>  RETURNS event_trigger
>  LANGUAGE plpgsql
> AS $function$
> declare
>   r record;
>   rc int;
> begin
>   for r in select * from pg_event_trigger_ddl_commands()
>   loop
>     if r.classid = 'pg_proc'::regclass and
>        exists(select * from pg_proc
>                 where oid = r.objid
>                   and prolang = (select oid from pg_language where lanname = 'plpgsql'))
>     then
>       perform * from plpgsql_check_function_tb(r.objid, fatal_errors=>false);
>       get diagnostics rc = row_count;
>       if (rc > 0) then
>         raise warning 'there are some errors or warnings (%) detected by plpgsql_check on function %', rc, r.objid::regprocedure;
>       end if;
>     end if;
>   end loop;
> end;
> $function$
> ;

How about to place this function into extension to use it so
```sql
create event trigger plpgsql_check_evtr on ddl_command_end execute function plpgsql_check_on_create_fx_trg_func();
```

**Comment by okbob** [comment]
po 6. 12. 2021 v 7:39 odesílatel RekGRpth ***@***.***> napsal:

> CREATE OR REPLACE FUNCTION public.check_on_create_fx_trg_func()
> RETURNS event_trigger
> LANGUAGE plpgsql
> AS $function$
> declare
> r record;
> rc int;
> begin
> for r in select * from pg_event_trigger_ddl_commands()
> loop
> if r.classid = 'pg_proc'::regclass and
> exists(select * from pg_proc
> where oid = r.objid
> and prolang = (select oid from pg_language where lanname = 'plpgsql'))
> then
> perform * from plpgsql_check_function_tb(r.objid, fatal_errors=>false);
> get diagnostics rc = row_count;
> if (rc > 0) then
> raise warning 'there are some errors or warnings (%) detected by
> plpgsql_check on function %', rc, r.objid::regprocedure;
> end if;
> end if;
> end loop;
> end;
> $function$
> ;
>
> How about to place this function into extension to use it so
>
> create event trigger plpgsql_check_evtr on ddl_command_end execute function plpgsql_check_on_create_fx_trg_func();
>
> I have no idea about parameters for plpgsql_check_function_tb. More - it
cannot work well with triggers functions :-/ because you cannot know in ddl
time the trigger relation.

So personally I don't think this usage of plpgsql_check is a good idea. I
can help a little bit, but this is not how  plpgsql_check should be used.
If somebody can use it like this, then he can make this trigger function.
It is not just preferred way :-)

**Comment by RekGRpth** [comment]
> I have no idea about parameters for plpgsql_check_function_tb

May be like TG_ARGV?

**Comment by okbob** [comment]
po 6. 12. 2021 v 7:52 odesílatel RekGRpth ***@***.***> napsal:

> I have no idea about parameters for plpgsql_check_function_tb
>
> May be like TG_ARGV?
>

The named arguments is not easy to pass by TG_ARGV - and it is more easy to
modify trigger function

**Comment by RekGRpth** [comment]
> I have no idea about parameters for plpgsql_check_function_tb

May be it is possible to realize it like every start (or fresh) ?

**Comment by okbob** [comment]
po 6. 12. 2021 v 10:53 odesílatel RekGRpth ***@***.***>
napsal:

> I have no idea about parameters for plpgsql_check_function_tb
>
> May be it is possible to realize it like every start (or fresh) ?
>

???

**Comment by RekGRpth** [comment]
Every start (or fresh), as I understand, does not require additional named arguments?

**Comment by okbob** [comment]
po 6. 12. 2021 v 11:16 odesílatel RekGRpth ***@***.***>
napsal:

> Every start (or fresh), as I understand, does not require additional named
> arguments?
>

sure - almost all arguments have default values. But you should specify an
argument if you want  to check performance, and if you want to check
trigger or polymorphic arguments.

You can use something like global session variables, but it can be a big
trap for a lot of users.

**Comment by RekGRpth** [comment]
> sure - almost all arguments have default values. But you should specify an argument if you want to check performance, and if you want to check trigger or polymorphic arguments. You can use something like global session variables, but it can be a big trap for a lot of users.

I want specify arguments via ... postgresql.conf file! Because they will same for all databases.

**Comment by okbob** [comment]
po 6. 12. 2021 v 11:44 odesílatel RekGRpth ***@***.***>
napsal:

> sure - almost all arguments have default values. But you should specify an
> argument if you want to check performance, and if you want to check trigger
> or polymorphic arguments. You can use something like global session
> variables, but it can be a big trap for a lot of users.
>
> I want specify arguments via ... postgresql.conf file! Because they will
> same for all databases.
>

you can do it if you want, but in your custom code. I don't want to
increase the complexity of the plpgsql_check interface. You can use GUC,
and you can do it like you want.
