### ISSUE TITLE
Please check if commit is in begin-end block with exception handling

### ISSUE THREAD

**Issue by M-Butter** [okbob/plpgsql_check#107]
When a commit statement in a procedure exists in a begin-end block with exception handling, then a runtime error will be raised with sqlstate =2D000 and sqlmessage = 'cannot commit while a subtransaction is active'. Will it be possible for you to identify this situation and signal it in plpgsql_check_function()?

See attached test file.
[testcase_commit_in_proc.txt](https://github.com/okbob/plpgsql_check/files/8530561/testcase_commit_in_proc.txt)

**Comment by okbob** [comment]
Hi

čt 21. 4. 2022 v 13:33 odesílatel M-Butter ***@***.***>
napsal:

> When a commit statement in a procedure exists in a begin-end block with
> exception handling, then a runtime error will be raised with sqlstate
> =2D000 and sqlmessage = 'cannot commit while a subtransaction is active'.
> Will it be possible for you to identify this situation and signal it in
> plpgsql_check_function()?
>
> See attached test file.
> testcase_commit_in_proc.txt
> <https://github.com/okbob/plpgsql_check/files/8530561/testcase_commit_in_proc.txt>
>

please, check last commit  cb1ae6e87d0581887d4999852a8aa443a3a43f52

Regards

Pavel

**Comment by M-Butter** [comment]
Hello Pavel,

Wow, you're fast!
It works like charm.

Thanks a lot,
Martin.

**Comment by okbob** [comment]
pá 22. 4. 2022 v 7:49 odesílatel M-Butter ***@***.***> napsal:

> Hello Pavel,
>
> Wow, you're fast!
> It works like charm.
>
:-)

Pavel
