### ISSUE TITLE
Postgres 14: procedure call to procedure with out parameter shows 'error:XX000:5:CALL:not enough default arguments'

### ISSUE THREAD

**Issue by M-Butter** [okbob/plpgsql_check#108]
Hello Pavel,

Since Postgres 14 it is possible to create a procedure with OUT parameters (where they should be INOUT in older versions). But when I do so, plpgsql_check_function() returns message like 'error:XX000:5:CALL:not enough default arguments' on the invoking procedure. See: [testcase_procedure_with_out_parameter.txt](https://github.com/okbob/plpgsql_check/files/8618741/testcase_procedure_with_out_parameter.txt).

Regards,
Martin.

**Comment by okbob** [comment]
st 4. 5. 2022 v 10:13 odesílatel M-Butter ***@***.***> napsal:

> Hello Pavel,
>
> Since Postgres 14 it is possible to create a procedure with OUT parameters
> (where they should be INOUT in older versions). But when I do so,
> plpgsql_check_function() returns message like 'error:XX000:5:CALL:not
> enough default arguments' on the invoking procedure. See:
> testcase_procedure_with_out_parameter.txt
> <https://github.com/okbob/plpgsql_check/files/8618741/testcase_procedure_with_out_parameter.txt>
> .
>

please, can you check master branch?

I fixed this issue (or similar issue last week)

**Comment by M-Butter** [comment]
I didn't pull the master branch before submitting this issue. Sorry for that, I'll try to remember to do so before complaining again.

But the master branch shows another issue: it doesn't allow the usage of constants any more.
See attachment:
[testcase_constant.txt](https://github.com/okbob/plpgsql_check/files/8619238/testcase_constant.txt).

Regards,
Martin.

**Comment by okbob** [comment]
should be fixed now (in 2.1.5), please check

**Comment by M-Butter** [comment]
Yep, you solved it.

Thanks,
Martin.

**Comment by okbob** [comment]
Thank you for report

Pavel


pá 6. 5. 2022 v 8:48 odesílatel M-Butter ***@***.***> napsal:
