### ISSUE TITLE
Pgloader - How to pass environment variables to connection string in PGsql  or load file directly

### ISSUE THREAD

**Issue by SamirMjs** [okbob/plpgsql_check#114]
LOAD CSV
FROM '/dbf/appworx/pgscript/temp_table_data.csv' (INV_ID)
INTO postgresql://username:password@hostname:portname/dbname
TARGET TABLE temp_inv_table

Running through shells script -

#!/bin/ksh

echo "Start"
#enviroment variable
. /xzy/DBset

echo "Fetching password value"

pgloader temp_table_load2.load

How do we pass value to temp_table_load2.load file using shell or if possible how we pass directly to load file
I am getting same above commented error.

Thanks you for help in advance

**Comment by okbob** [comment]
Hi

what is revelation to plpgsql_check?



út 7. 6. 2022 v 15:30 odesílatel SamirMjs ***@***.***> napsal:
