### ISSUE TITLE
Ability to check dynamic sqls

### ISSUE THREAD

**Issue by plotn** [okbob/plpgsql_check#119]
Hi!

We recently begun using plpgsql_check and found it very usable. I even did a DBever contribution to add button "Check" to sql edit window. But the problem is as follows - I cant check dynamic sql, but it could be often usable. Lets take an example - we need to develop flexible search function with many conditions and custom sort, so we write:

select * from X where A = :A and B = :B and D = :D order by A desc, B, C desc

so we can write a function (returning resultset) with sql inside:

... where (A = :A or :A is null) and (B = :B or :B is null)

Much complex (and maybe could affect query plan), i think.
Futher, we cant parametrize ORDER BY and we need always rewrite it (there are some examples with case clause, but they are complex too).

What is the way we want to go:

1. To have a "template" SQL without where (or with static part);
2. To construct where and order_by dynamically.

Lets do this:
sql_template = 'select * from X';
sql_final = sql_template || where_part || order_by_part;
execute sql_final;

What do we miss? We miss sql checking. What if we can say hint to plpgsql_check to check some string additionally? e.g. IntellijIdea can parse and check SQLs in strings and this is very ok. Lets imagine:

sql_template = '/*check*/ select * from X /*no_check*/ maybe_placeholder_that_shoud_be_skipped /*check*/ other_part';
...
and the sql to check will be "select * from X other_part"

**Comment by okbob** [comment]
Hi

so 27. 8. 2022 v 11:25 odesílatel plotn ***@***.***> napsal:

> Hi!
>
> We recently begun using plpgsql_check and found it very usable. I even did
> a DBever contribution to add button "Check" to sql edit window. But the
> problem is as follows - I cant check dynamic sql, but it could be often
> usable. Lets take an example - we need to develop flexible search function
> with many conditions and custom sort, so we write:
>
> select * from X where A = :A and B = :B and D = :D order by A desc, B, C
> desc
>
> so we can write a function (returning resultset) with sql inside:
>
> ... where (A = :A or :A is null) and (B = :B or :B is null)
>
> Much complex (and maybe could affect query plan), i think.
> Futher, we cant parametrize ORDER BY and we need always rewrite it (there
> are some examples with case clause, but they are complex too).
>
> What is the way we want to go:
>
>    1. To have a "template" SQL without where (or with static part);
>    2. To construct where and order_by dynamically.
>
> Lets do this:
> sql_template = 'select * from X';
> sql_final = sql_template || where_part || order_by_part;
> execute sql_final;
>
> What do we miss? We miss sql checking. What if we can say hint to
> plpgsql_check to check some string additionally? e.g. IntellijIdea can
> parse and check SQLs in strings and this is very ok. Lets imagine:
>
> sql_template = '/*check*/ select * from X /*no_check*/
> maybe_placeholder_that_shoud_be_skipped /*check*/ other_part';
> ...
> and the sql to check will be "select * from X other_part"
>
plpgsql_check doesn't execute any assignment  statement. So sql_final
inside plpgsql_check has always NULL value.

More - plpgsql_check doesn't contain SQL parser. SQL is a terrible language
for parsing. IntellijIdea has its own customized fault tolerant parsers -
plpgsql_check can use just a very strict parser from Postgres.

Maybe some work can be done by introducing a new pragma, but I am afraid
the new code will be terribly unlean.
