### ISSUE TITLE
The title of the project "reads" funny

### ISSUE THREAD

**Issue by kirkw** [okbob/plpgsql_check#124]
Currently:
plpgsql_check is linter tool for language PL/pgSQL (native language for PostgreSQL store procedures).

Better:
plpgsql_check is a linter tool for the PostgreSQL language plpgsql (the native language for PostgreSQL store procedures).

[This improves SEO because nobody searches for PL/pgSQL, they search for Postgresql or plpgsql (case is not important, but SLASH is)

Best:
plpgsql_check is the best linter tool for the PostgreSQL language plpgsql (the native language for PostgreSQL store procedures).

Now, this is considering what people MIGHT search for.  Your tool always comes up #1 when I search for plpgsql lint or linter.
Which is great.  Also, I don't really know of any other linters for plpgsl... So I think you can take the claim.  It is up to you.
The Original wording leaves a lot to be desired.  (That said.  I barely speak 1 language... making me American, LOL)

**Comment by okbob** [comment]
updated, thank you for tip

**Comment by okbob** [comment]
ne 18. 9. 2022 v 21:54 odesílatel Kirk Wolak ***@***.***>
napsal:

> Currently:
> plpgsql_check is linter tool for language PL/pgSQL (native language for
> PostgreSQL store procedures).
>
> Better:
> plpgsql_check is a linter tool for the PostgreSQL language plpgsql (the
> native language for PostgreSQL store procedures).
>

I like this version


> [This improves SEO because nobody searches for PL/pgSQL, they search for
> Postgresql or plpgsql (case is not important, but SLASH is)
>
> Best:
> plpgsql_check is the best linter tool for the PostgreSQL language plpgsql
> (the native language for PostgreSQL store procedures).
>
It is just one - so the best is not correct - although it sounds
majestically :). I am not sure if people knows the word "linter"
