### ISSUE TITLE
errrror on make install

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#126]
building from master, since the last change I get
/usr/bin/install: cannot stat './/plpgsql_check--2.2.sql': No such file or directory
make: *** [/u01/app/postgres/product/15dev/lib/pgxs/src/makefiles/pgxs.mk:240: install] Error 1

maybe as  plpgsql_check--2.1.sql got removed, but not plpgsql_check--2.2.sql added?

**Comment by okbob** [comment]
st 21. 9. 2022 v 21:09 odesílatel neiaberau ***@***.***>
napsal:

> building from master, since the last change I get
> /usr/bin/install: cannot stat './/plpgsql_check--2.2.sql': No such file or
> directory
> make: *** [/u01/app/postgres/product/15dev/lib/pgxs/src/makefiles/
> pgxs.mk:240: install] Error 1
>
> maybe as plpgsql_check--2.1.sql got removed, but not plpgsql_check--2.2.sq
> added?
>

my bad

I forgot it add to git

It should be fixed now at 2.2.1

Thank you for bug report

**Comment by neiaberau** [comment]
thanks a lot for the quick fix
