### ISSUE TITLE
compile failure using latest postgres master 

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#134]
not urgent,  just to let you know

Compiling adventurously against latest postgres master gives

....
      |        ^~~~~~~~~~~~~~~
src/check_function.c:1320:4: error: too few arguments to function ‘ProcessGUCArray’

this seems to have been changed in commit 096dd80f3c on master branch of postgres on 09-12-2022

**Comment by okbob** [comment]
should be fixed now, 

thank you for bug report

**Comment by neiaberau** [comment]
that was fast, faster than me eating dinner, thanks a lot
