### ISSUE TITLE
compile error with postgres master branch

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#136]
not  urgent, just got another error when trying to build, which worked before:

I get
src/parser.c: In function ‘get_type_internal’:
src/parser.c:814:13: error: too few arguments to function ‘typeStringToTypeName’
  814 |  typeName = typeStringToTypeName(typestr);
      |             ^~~~~~~~~~~~~~~~~~~~
In file included from src/parser.c:19:
/u01/app/postgres/product/16dev/include/server/parser/parse_type.h:54:18: note: declared here
   54 | extern TypeName *typeStringToTypeName(const char *str, Node *escontext);
      |                  ^~~~~~~~~~~~~~~~~~~~

probably related to postgres commit
 git show --stat 858e776c84f

**Comment by okbob** [comment]
should be fixed now, thank you for echo

**Comment by neiaberau** [comment]
perfect
