### ISSUE TITLE
improve error message

### ISSUE THREAD

**Issue by surajkharage19** [okbob/plpgsql_check#139]
While browsing the code, found the below error message which I feel is incomplete, the especially second part of the message.

```
if (PG_NARGS() != 19)
		elog(ERROR, "unexpected number of parameters, you should to update extension");
```

There are multiple occurrences of such error messages, can we improve this?

**Comment by okbob** [comment]
st 8. 3. 2023 v 13:16 odesílatel surajkharage19 ***@***.***>
napsal:

> While browsing the code, found the below error message which I feel is
> incomplete, the especially second part of the message.
>
> if (PG_NARGS() != 19)
> 		elog(ERROR, "unexpected number of parameters, you should to update extension");
>
> There are multiple occurrences of such error messages, can we improve this?
>

I think this message is ok. It is just a safeguard against a situation when
people do library updates, but without related the extension (sql script)
update.

Maybe  generally this check is too primitive, and can be implemented
better, but I have no idea how. Maybe we can check the signature of the
function with the expected signature.

This is maybe a generic issue of Postgres so we are not able to ensure
correct versions of so file and sql script file.

**Comment by okbob** [comment]
st 8. 3. 2023 v 15:07 odesílatel Pavel Stehule ***@***.***>
napsal:

>
>
> st 8. 3. 2023 v 13:16 odesílatel surajkharage19 ***@***.***>
> napsal:
>
>> While browsing the code, found the below error message which I feel is
>> incomplete, the especially second part of the message.
>>
>> if (PG_NARGS() != 19)
>> 		elog(ERROR, "unexpected number of parameters, you should to update extension");
>>
>> There are multiple occurrences of such error messages, can we improve
>> this?
>>
>
> I think this message is ok. It is just a safeguard against a situation
> when people do library updates, but without related the extension (sql
> script) update.
>
> Maybe  generally this check is too primitive, and can be implemented
> better, but I have no idea how. Maybe we can check the signature of the
> function with the expected signature.
>

you can get an oid of currently called function from flinfo->fn_oid. By
using dependencies you can search owning extension, and you can read
extversion and compare it with hardcoded constant in C file. It can works
and it can be called only once per session for all functions when this
check is ok.

**Comment by kirkw** [comment]
We should fix the English in that error message:

```
if (PG_NARGS() != 19)
		elog(ERROR, "unexpected number of parameters, you should DO update extension");

```

Obviously without upper case...

**Comment by okbob** [comment]
st 8. 3. 2023 v 16:28 odesílatel Kirk Wolak ***@***.***>
napsal:

> We should fix the English in that error message:
>
> if (PG_NARGS() != 19)
> 		elog(ERROR, "unexpected number of parameters, you should DO update extension");
>
>
> Obviously without upper case...
>
+1

send pull request please

Pavel

**Comment by okbob** [comment]
see b0970ff

**Comment by surajkharage19** [comment]
Thanks, Pavel for your prompt action on this. Marking this as closed.
