### ISSUE TITLE
Few macros declared twice

### ISSUE THREAD

**Issue by surajkharage19** [okbob/plpgsql_check#141]
Hi,

Noticed that a few macros such as NEVER_READ_VARIABLE_TEXT, UNUSED_PARAMETER_TEXT etc from src/plpgsql_check.h declared twice. We can get rid of it.

**Comment by okbob** [comment]
Hi


čt 23. 3. 2023 v 15:11 odesílatel surajkharage19 ***@***.***>
napsal:

> Hi,
>
> Noticed that a few macros such as NEVER_READ_VARIABLE_TEXT,
> UNUSED_PARAMETER_TEXT etc from src/plpgsql_check.h declared twice. We can
> get rid of it.
>

should be fixed by  a8ec0a4063047fe2da3c93933722d13ca4ec18ed

Regards

Pavel

**Comment by surajkharage19** [comment]
Looks good. Thanks. Closing this ticket.

**Comment by okbob** [comment]
Thank you for report.

pá 24. 3. 2023 v 3:31 odesílatel surajkharage19 ***@***.***>
napsal:
