### ISSUE TITLE
ERROR install extension inside  Docker container 

### ISSUE THREAD

**Issue by johndiego** [okbob/plpgsql_check#142]
Hi guys,
we can help install extension inside container look.

Step 6/15 : FROM postgres:15 as database
 ---> 3b6645d2c145
Step 7/15 : RUN apt-get update && apt-get -y install git curl ca-certificates gnupg build-essential postgresql-server-dev-15 postgresql-15-pldebugger nano
 ---> Using cache
 ---> ec805fda80b8
Step 8/15 : RUN git clone https://github.com/citusdata/pg_cron.git
 ---> Using cache
 ---> 4aab06f443dd
Step 9/15 : RUN cd pg_cron && make && make install
 ---> Using cache
 ---> 032773fcdca8
Step 10/15 : RUN curl -s -L https://github.com/theory/pgtap/archive/v1.2.0.tar.gz | tar zxvf - && cd pgtap-1.2.0 && make && make install
 ---> Using cache
 ---> 906439e9b537
Step 11/15 : RUN curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
 ---> Using cache
 ---> 8c25c52d1b0c
Step 12/15 : RUN git clone https://github.com/okbob/plpgsql_check
 ---> Using cache
 ---> 4b3f6c5f04cc
Step 13/15 : RUN cd plpgsql_check && make USE_PGXS=1 clean && make USE_PGXS=1 install && make clean && make install
 ---> Running in d46187e15ef9
rm -f plpgsql_check.so   libplpgsql_check.a  libplpgsql_check.pc
rm -f src/assign.o src/catalog.o src/check_expr.o src/check_function.o src/expr_walk.o src/format.o src/parser.o src/plpgsql_check.o src/pragma.o src/profiler.o src/report.o src/stmtwalk.o src/tablefunc.o src/tracer.o src/typdesc.o src/assign.bc src/catalog.bc src/check_expr.bc src/check_function.bc src/expr_walk.bc src/format.bc src/parser.bc src/plpgsql_check.bc src/pragma.bc src/profiler.bc src/report.bc src/stmtwalk.bc src/tablefunc.bc src/tracer.bc src/typdesc.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/assign.o src/assign.c
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/catalog.o src/catalog.c
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/check_expr.o src/check_expr.c
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/check_function.o src/check_function.c
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/expr_walk.o src/expr_walk.c
gcc -g -fPIC -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/15/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/format.o src/format.c
[91mIn file included from /usr/include/postgresql/15/server/tsearch/ts_locale.h:20,
                 from src/format.c:18:
/usr/include/postgresql/15/server/utils/pg_locale.h:19:10: fatal error: unicode/ucol.h: No such file or directory
   19 | #include <unicode/ucol.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by okbob** [comment]
út 9. 5. 2023 v 15:04 odesílatel johndiego ***@***.***>
napsal:

> Hi guys,
> we can help install extension inside container look.
> Step 6/15 : FROM postgres:15 as database ---> 3b6645d2c145 Step 7/15 : RUN
> apt-get update && apt-get -y install git curl ca-certificates gnupg
> build-essential postgresql-server-dev-15 postgresql-15-pldebugger nano --->
> Using cache ---> ec805fda80b8 Step 8/15 : RUN git clone
> https://github.com/citusdata/pg_cron.git ---> Using cache --->
> 4aab06f443dd Step 9/15 : RUN cd pg_cron && make && make install ---> Using
> cache ---> 032773fcdca8 Step 10/15 : RUN curl -s -L
> https://github.com/theory/pgtap/archive/v1.2.0.tar.gz | tar zxvf - && cd
> pgtap-1.2.0 && make && make install ---> Using cache ---> 906439e9b537 Step
> 11/15 : RUN curl -fsSL
> https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh
> ---> Using cache ---> 8c25c52d1b0c Step 12/15 : RUN git clone
> https://github.com/okbob/plpgsql_check ---> Using cache ---> 4b3f6c5f04cc
> Step 13/15 : RUN cd plpgsql_check && make USE_PGXS=1 clean && make
> USE_PGXS=1 install && make clean && make install ---> Running in
> d46187e15ef9 rm -f plpgsql_check.so libplpgsql_check.a libplpgsql_check.pc
> rm -f src/assign.o src/catalog.o src/check_expr.o src/check_function.o
> src/expr_walk.o src/format.o src/parser.o src/plpgsql_check.o src/pragma.o
> src/profiler.o src/report.o src/stmtwalk.o src/tablefunc.o src/tracer.o
> src/typdesc.o src/assign.bc src/catalog.bc src/check_expr.bc
> src/check_function.bc src/expr_walk.bc src/format.bc src/parser.bc
> src/plpgsql_check.bc src/pragma.bc src/profiler.bc src/report.bc
> src/stmtwalk.bc src/tablefunc.bc src/tracer.bc src/typdesc.bc rm -rf
> results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/
> output_iso/ gcc -g -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/assign.o src/assign.c gcc -g
> -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/catalog.o src/catalog.c gcc
> -g -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/check_expr.o
> src/check_expr.c gcc -g -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/check_function.o
> src/check_function.c gcc -g -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/expr_walk.o src/expr_walk.c
> gcc -g -fPIC
> -I/usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/15/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -c -o src/format.o src/format.c
> �[91mIn file included from
> /usr/include/postgresql/15/server/tsearch/ts_locale.h:20, from
> src/format.c:18: /usr/include/postgresql/15/server/utils/pg_locale.h:19:10:
> fatal error: unicode/ucol.h: No such file or directory 19 | #include
> <unicode/ucol.h> | ^~~~~~~~~~~~~~~~ compilation terminated.
>
first you cannot compile this extension. Installation is another step.

You miss libicu

It is similar issue like https://github.com/akorotkov/vgram/issues/1

**Comment by johndiego** [comment]
@okbob  thanks this solved =) sorry for newbe!!

**Comment by okbob** [comment]
út 9. 5. 2023 v 20:32 odesílatel johndiego ***@***.***>
napsal:

> @okbob <https://github.com/okbob> thanks this solved =) sorry for newbe!!
>
no problem :-)
