### ISSUE TITLE
compile error on postgres master branch

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#143]
just for info, somehow my nightly build  failed with:

#0 1.297 src/check_function.c: In function ‘load_configuration’:
#0 1.297 src/check_function.c:1196:8: error: incompatible type for argument 2 of ‘ProcessGUCArray’
#0 1.297  1196 |        NULL,
#0 1.297       |        ^~~~
#0 1.297       |        |
#0 1.297       |        void *
#0 1.297 In file included from src/check_function.c:18:
#0 1.297 /u01/app/postgres/product/16dev/include/server/utils/guc.h:395:19: note: expected ‘GucContext’ but argument is of type ‘void *’
#0 1.297   395 |        GucContext context, GucSource source, GucAction action);
#0 1.297       |        ~~~~~~~~~~~^~~~~~~
#0 1.297 src/check_function.c:1192:4: error: too many arguments to function ‘ProcessGUCArray’
#0 1.297  1192 |    ProcessGUCArray(set_items,
#0 1.297       |    ^~~~~~~~~~~~~~~
#0 1.297 In file included from src/check_function.c:18:
#0 1.297 /u01/app/postgres/product/16dev/include/server/utils/guc.h:394:13: note: declared here
#0 1.297   394 | extern void ProcessGUCArray(ArrayType *array,
#0 1.297       |             ^~~~~~~~~~~~~~~
#0 1.319 make: *** [<builtin>: src/check_function.o] Error 1

it seems something change in commit b9a7a82272 on the postgres master branch in src/backend/utils/misc/guc.c

**Comment by okbob** [comment]
Hi


čt 18. 5. 2023 v 10:19 odesílatel neiaberau ***@***.***>
napsal:

> just for info, somehow my nightly build failed with:
>
> #0 1.297 src/check_function.c: In function ‘load_configuration’:
> #0 1.297 src/check_function.c:1196:8: error: incompatible type for
> argument 2 of ‘ProcessGUCArray’
> #0 1.297 1196 | NULL,
> #0 1.297 | ^~~~
> #0 1.297 | |
> #0 1.297 | void *
> #0 1.297 In file included from src/check_function.c:18:
> #0 1.297
> /u01/app/postgres/product/16dev/include/server/utils/guc.h:395:19: note:
> expected ‘GucContext’ but argument is of type ‘void *’
> #0 1.297 395 | GucContext context, GucSource source, GucAction action);
> #0 1.297 | ~~~~~~~~~~~^~~~~~~
> #0 1.297 src/check_function.c:1192:4: error: too many arguments to
> function ‘ProcessGUCArray’
> #0 1.297 1192 | ProcessGUCArray(set_items,
> #0 1.297 | ^~~~~~~~~~~~~~~
> #0 1.297 In file included from src/check_function.c:18:
> #0 1.297
> /u01/app/postgres/product/16dev/include/server/utils/guc.h:394:13: note:
> declared here
> #0 1.297 394 | extern void ProcessGUCArray(ArrayType *array,
> #0 1.297 | ^~~~~~~~~~~~~~~
> #0 1.319 make: *** [: src/check_function.o] Error 1
>
> it seems something change in commit b9a7a82272 on the postgres master
> branch in src/backend/utils/misc/guc.c
>

Thank you for info

Regards

Pavel

**Comment by okbob** [comment]
should be fixed now

**Comment by neiaberau** [comment]
thanks a lot for the super fast fix
