### ISSUE TITLE
Getting an error getting the dependency table for functions with ANYELEMENT types?

### ISSUE THREAD

**Issue by kirkw** [okbob/plpgsql_check#144]
The simplest example is this:
CREATE OR REPLACE FUNCTION netcomp.ufn_isnumber(anyelement)
 RETURNS integer
 LANGUAGE plpgsql
 IMMUTABLE STRICT
AS $function$
DECLARE
  x VARCHAR;
BEGIN
  x = $1 :: NUMERIC;
  RETURN 1;
EXCEPTION
  WHEN SQLSTATE '22P02' THEN
    RETURN 0;
END;
$function$

Then calling plpgsql_show_dependency_tb() throws an error. (I may not have the latest version)

select '18879005'::oid::regprocedure;
       regprocedure
--------------------------
 ufn_isnumber(anyelement)
(1 row)

Time: 0.679 ms

select * from plpgsql_show_dependency_tb('18879005'::oid);

ERROR:  cache lookup failed for type 0
CONTEXT:  SQL function "plpgsql_show_dependency_tb" statement 1
STATEMENT:  select * from plpgsql_show_dependency_tb('18879005'::oid);
Time: 0.814 ms

**Comment by okbob** [comment]
should be fixed by 8385e12af47209a998828c84fb4030b50cb0e4c2

note: you can use call `select * from plpgsql_show_dependency_tb('ufn_isnumber'::regproc)` or just `select * from plpgsql_show_dependency_tb('ufn_isnumber')`

**Comment by kirkw** [comment]
Thanks for fixing this, but I get this error, and the ALTER says it is missing the SQL to upgrade, and doesn't change the version?

11:08:17 devuser@nctest= > select * from plpgsql_show_dependency_tb('18879005'::oid);
ERROR:  extension "plpgsql_check" is not updated in system catalog
DETAIL:  version "2.4" is required, version "2.2" is installed
HINT:  execute "ALTER EXTENSION plpgsql_check UPDATE TO '2.4'"
CONTEXT:  SQL function "plpgsql_show_dependency_tb" statement 1
STATEMENT:  select * from plpgsql_show_dependency_tb('18879005'::oid);
Time: 4.444 ms

11:08:25 devuser@nctest= > set role postgres;
Time: 0.549 ms
11:08:52 devuser@nctest= # ALTER EXTENSION plpgsql_check UPDATE TO '2.4';

ERROR:  extension "plpgsql_check" has no update path from version "2.2" to version "2.4"
STATEMENT:  ALTER EXTENSION plpgsql_check UPDATE TO '2.4';

**Comment by kirkw** [comment]
As a NOTE, dropping, and recreating the extension fixed it.

**Comment by kirkw** [comment]
Side note.. I struggled building version 14 with version 15 installed.  It only wanted to make for version 15 (which I don't have source for, Ubuntu brought it down for me).  Anyways, I renamed the /15 folder to /13 so I could make/install this.

I assume there would be an easier way to say:
make -D version=14

or something?

**Comment by okbob** [comment]
ne 28. 5. 2023 v 17:17 odesílatel Kirk Wolak ***@***.***>
napsal:

> As a NOTE, dropping, and recreating the extension fixed it.
>

yes, plpgsql_check doesn't support updates.

**Comment by okbob** [comment]
ne 28. 5. 2023 v 17:19 odesílatel Kirk Wolak ***@***.***>
napsal:

> Side note.. I struggled building version 14 with version 15 installed. It
> only wanted to make for version 15 (which I don't have source for, Ubuntu
> brought it down for me). Anyways, I renamed the /15 folder to /13 so I
> could make/install this.
>
> I assume there would be an easier way to say:
> make -D version=14
>
> or something?
>

Debian (Ubuntu) has its own build system, that I don't know, because I am
exclusively a RH user. I found https://github.com/dimitri/pgextwlist#install

I found (by google)
https://manpages.ubuntu.com/manpages/impish/man1/pg_buildext.1.html

The version cannot be specified by identifier, you should set PATH to some
directories with PostgreSQL files (probably pg_config is important). It
should be possible to build extensions without PostgreSQL source codes. You
need to install some devel packages.

https://www.postgresql.org/docs/current/extend-pgxs.html

**Comment by kirkw** [comment]
Okay, thank you.

BTW, I found a strange behavior.
select plpgsql_show_dependency_tb('18878012'::oid, null::oid);

Will return NOTHING.  Here is the problem.  I am processing all functions, including triggers.
And I am finding the ONE relation (or NULL) for all non-trigger functions.

Unfortunately, it looks like passing a NULL value in, directly, causes ZERO rows to be returned.
So, I will have to basically do 2 inserts, one for a call to this function without NULL (no second parameter),
and another with the relid::oid being set.

This seems like as long as I pass in NULL, it should work.
Also, I tried passing in a REAL relid  for non-trigger functions, but that dies with a proper error message.

Thanks.

Kirk Out!

**Comment by okbob** [comment]
ne 28. 5. 2023 v 22:26 odesílatel Kirk Wolak ***@***.***>
napsal:

> Okay, thank you.
>
> BTW, I found a strange behavior.
> select plpgsql_show_dependency_tb('18878012'::oid, null::oid);
>
> Will return NOTHING. Here is the problem. I am processing all functions,
> including triggers.
> And I am finding the ONE relation (or NULL) for all non-trigger functions.
>
> Unfortunately, it looks like passing a NULL value in, directly, causes
> ZERO rows to be returned.
> So, I will have to basically do 2 inserts, one for a call to this function
> without NULL (no second parameter),
> and another with the relid::oid being set.
>
> This seems like as long as I pass in NULL, it should work.
> Also, I tried passing in a REAL relid for non-trigger functions, but that
> dies with a proper error message.
>

it is correct

This function is marked as STRICT - so any null arguments forces empty or
NULL result.

you can look on definition

CREATE FUNCTION plpgsql_show_dependency_tb(fnname text,
                                           relid regclass DEFAULT 0,
                                           anyelememttype regtype DEFAULT
'int',
                                           anyenumtype regtype DEFAULT '-',
                                           anyrangetype regtype DEFAULT
'int4range',
                                           anycompatibletype regtype
DEFAULT 'int',
                                           anycompatiblerangetype regtype
DEFAULT 'int4range')

you should to use 0 instead NULL, or you can use mixed notation like

SELECT plpgsql_show_dependency_tb('foo', anyelememttype => 'varchar');



Thanks.

**Comment by kirkw** [comment]
Thank you.  Setting it to Zero.
I should have looked closer at the function (Clearly).
I struggled for like 1hr on why it was acting funny.  But only in some situations (passing, NULL as I eventually discovered).

You can close this down.
Deeply Appreciated!
