### ISSUE TITLE
When checking triggers, tg_table_name is not taken into account

### ISSUE THREAD

**Issue by andruche** [okbob/plpgsql_check#148]
How to reproduce:

```sql
create or replace function tg_ab() returns trigger as $$
declare
  val text;
begin
  if tg_table_name = 'a' then
    val := new.val_a;
  else
    val := new.val_b;
  end if;

  --some code

  return new;
end;
$$ language plpgsql;

create table a(
  id integer,
  val_a text
);

create table b(
  id integer,
  val_b text
);

create trigger ins_a
  after insert on a
  for each row execute function tg_ab();

create trigger ins_b
  after insert on b
  for each row execute function tg_ab();


--check query from README:
-- check all trigger plpgsql functions
SELECT p.proname, tgrelid::regclass, cf.*
   FROM pg_proc p
        JOIN pg_trigger t ON t.tgfoid = p.oid 
        JOIN pg_language l ON p.prolang = l.oid
        JOIN pg_namespace n ON p.pronamespace = n.oid,
        LATERAL plpgsql_check_function(p.oid, t.tgrelid) cf
  WHERE n.nspname = 'public' and l.lanname = 'plpgsql';


 proname | tgrelid |                             cf
---------+---------+------------------------------------------------------------
 tg_ab   | a       | error:42703:8:assignment:record "new" has no field "val_b"
 tg_ab   | a       | Context: SQL statement "SELECT new.val_b"
 tg_ab   | b       | error:42703:6:assignment:record "new" has no field "val_a"
 tg_ab   | b       | Context: SQL statement "SELECT new.val_a"
(4 rows)
```

Function plpgsql_check_function() detects 2 errors, although everything is fine.

It would be great if it didn't go to branches for which the condition tg_table_name (current relid) = 'some_table' is not met.

**Comment by okbob** [comment]
Hi

čt 17. 8. 2023 v 19:02 odesílatel Andrey Chernyakov <
***@***.***> napsal:

> How to reproduce:
>
> create or replace function tg_ab() returns trigger as $$
> declare
>   val text;begin
>   if tg_table_name = 'a' then
>     val := new.val_a;
>   else
>     val := new.val_b;
>   end if;
>
>   --some code
>
>   return new;
> end;
> $$ language plpgsql;
> create table a(
>   id integer,
>   val_a text
> );
> create table b(
>   id integer,
>   val_b text
> );
> create trigger ins_a
>   after insert on a
>   for each row execute function tg_ab();
> create trigger ins_b
>   after insert on b
>   for each row execute function tg_ab();
>
> --check query from README:-- check all trigger plpgsql functionsSELECT p.proname, tgrelid::regclass, cf.*
>    FROM pg_proc p
>         JOIN pg_trigger t ON t.tgfoid = p.oid
>         JOIN pg_language l ON p.prolang = l.oid
>         JOIN pg_namespace n ON p.pronamespace = n.oid,
>         LATERAL plpgsql_check_function(p.oid, t.tgrelid) cf
>   WHERE n.nspname = 'public' and l.lanname = 'plpgsql';
>
>
>  proname | tgrelid |                             cf---------+---------+------------------------------------------------------------
>  tg_ab   | a       | error:42703:8:assignment:record "new" has no field "val_b"
>  tg_ab   | a       | Context: SQL statement "SELECT new.val_b"
>  tg_ab   | b       | error:42703:6:assignment:record "new" has no field "val_a"
>  tg_ab   | b       | Context: SQL statement "SELECT new.val_a"
> (4 rows)
>
> Function plpgsql_check_function() detects 2 errors, although everything is
> fine.
>
> It would be great if it didn't go to branches for which the condition
> tg_table_name (current relid) = 'some_table' is not met.
>
Probably it is implementable - but for correct implementation you should
implement checks for all TG_XXX variables, and sometimes TG_OP can contain
three values, and the expression can be written very differently. So the
implementation can require a few weeks, and without some stronger
sponzoring, I don't want to do it in my free time. It is not too easy.

**Comment by okbob** [comment]
After some thinking, I don't think so it is implementable with current design. It needs strong redesign how plpgsql works with variables. As workaround, you can disable check there pragma:
```
CREATE OR REPLACE FUNCTION public.tg_ab()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$                                  
declare                                               
  val text;                                                
begin                                                  
  if tg_table_name = 'a' then
    -- pragma has local local block scope, so is not necessary to enable it again 
    perform 'pragma:disable:check';
    val := new.val_a;
  else
    perform 'pragma:disable:check';
    val := new.val_b;
  end if;

  raise notice '% %', new.id, val;
  --some code

  return new;
end;
$function$
;

**Comment by andruche** [comment]
Thank you!
I didn't know about "perform 'pragma:disable:check'".
It looks quite usable)
