### ISSUE TITLE
PostgreSQL 15 don't start because of conflicts with another extensions.

### ISSUE THREAD

**Issue by Tiago-Anastacio** [okbob/plpgsql_check#152]
Hello,
I am using plpgsql check release 2.3 and PostgreSQL 13,14 and 15
From PostgreSQL 15, there is an incompatibility with plpgsql_check and some extensions => PostgreSQL just don't start

Some of these extensions are very important : pglogical

I know that from PostgresQL 15 , there is a change on the way hooks are handled in shared memory, But I don't know exactly how

Thanks

**Comment by okbob** [comment]
plpgsql_check uses correct handling of shared memory now. Do you have latest version of plpgsql_check? There was some bugfixes in this area - https://github.com/okbob/plpgsql_check/commit/8327afbfb3fa0470ed7af5f398c66a7362cb323c

**Comment by Tiago-Anastacio** [comment]
I am using this package from community repository:
https://download.postgresql.org/pub/repos/zypp/15/suse/sles-15.4-x86_64/plpgsql_check_15-2.3.4-1.sles15.1.x86_64.rpm

**Comment by Tiago-Anastacio** [comment]
also have these packages available:
https://download.postgresql.org/pub/repos/zypp/15/suse/sles-15.4-x86_64/plpgsql_check_15-2.3.1-1.sles15.x86_64.rpm         21-Feb-2023 10:09              266504
https://download.postgresql.org/pub/repos/zypp/15/suse/sles-15.4-x86_64/plpgsql_check_15-2.3.2-1.sles15.x86_64.rpm)         10-May-2023 20:17              267096
[plpgsql_check_15-2.3.4-1.sles15.1.x86_64.rpm](https://download.postgresql.org/pub/repos/zypp/15/suse/sles-15.4-x86_64/plpgsql_check_15-2.3.4-1.sles15.1.x86_64.rpm)       04-Jun-2023 01:23              270048
https://download.postgresql.org/pub/repos/zypp/15/suse/sles-15.4-x86_64/plpgsql_check_15-2.3.4-1.sles15.x86_64.rpm         18-Apr-2023 15:53              270376

**Comment by okbob** [comment]
Unfortunately, plpgsql_check uses badly named global variables - same issue is in pglogical. It should be fixed by b55a8a147f1a23facc09589167ce4ff04c2a1578

**Comment by Tiago-Anastacio** [comment]
Thanks Pavel.
Could you please ask Devrim to package new releases 2.4 and 2.5 (they are not in the community repositery) ?
If I ask it will take much more time...
Thank you

**Comment by okbob** [comment]
pá 15. 9. 2023 v 12:03 odesílatel T.Anastacio ***@***.***>
napsal:

> Thanks Pavel.
> Could you please ask Devrim to package new releases 2.4 and 2.5 (they are
> not in the community repositery) ?
>
the fix is only in 2.5 version

I'll mail to Devrim

**Comment by okbob** [comment]
The community packages are updated https://download.postgresql.org/pub/repos/yum/16/redhat/rhel-9-x86_64/
