### ISSUE TITLE
Cannot determine result of dynamic SQL

### ISSUE THREAD

**Issue by spk-615** [okbob/plpgsql_check#159]
Hello,

'plpgsql_check' cannot determine result of dynamic SQL if passed from variable:

Here is an example:

```sql
  begin;

  create or replace function tabret_dynamic()
    returns table (id integer, val text) as
  $$
  declare
    z_query text;
  begin
    z_query := 'select id, val from (values (1, ''a''), (2, ''b'')) as v(id, val)';

    return query
      execute z_query;
  end;
  $$ language plpgsql immutable;

  select * from plpgsql_check_function('tabret_dynamic()');

  rollback;
```

which results in following warning:

> warning extra:00000:OUT variable "id" is maybe unmodified
>  Detail: cannot to determine result of dynamic SQL
> warning extra:00000:OUT variable "val" is maybe unmodified
>  Detail: cannot to determine result of dynamic SQL

What's interesting if we pass query string directly to execute, the warning doesn't occur:

```sql
  begin;

  create or replace function tabret_dynamic()
    returns table (id integer, val text) as
  $$
  begin
    return query
      execute 'select id, val from (values (1, ''a''), (2, ''b'')) as v(id, val)';
  end;
  $$ language plpgsql immutable;

  select * from plpgsql_check_function('tabret_dynamic()');

  rollback;
```

**Comment by okbob** [comment]
Unfortunately, this is expected behaviour - plpgsql_check doesn't know what is inside the variable. Maybe once I'll write support for this kind of analyse, but I have not any idea when it can be. The partial support can be messy, and full support is lot of work and this is unpaid project.

**Comment by spk-615** [comment]
Hi, thank You for calrification.
I didn't understand complexity of this problem.

**Comment by okbob** [comment]
you can check 2.6 release where some issues like yours should be fixed d47c3c63911c1ebac88753ccadd4eac50bd75a06

**Comment by spk-615** [comment]
Thank You.
Unfortunately, my real case is a bit more complex, so I'll have to live with warnings or find some work-around.

**Comment by okbob** [comment]
so 4. 11. 2023 v 0:58 odesílatel spk-615 ***@***.***> napsal:

> Thank You.
> Unfortunately, my real case is a bit more complex, so I'll have to live
> with warnings or find some work-around.
>
you can disable warnings by using plpgsql_check's pragmas

https://github.com/okbob/plpgsql_check#pragma
