### ISSUE TITLE
Question: A way to EXTEND the SQL Validation of EXECUTE 'UDPATE ...';  to specific functions:  util.sql_exec('UPDATE ...' );

### ISSUE THREAD

**Issue by kirkw** [okbob/plpgsql_check#163]
We have a wrapper function for EXECUTE, and did not realize that plpgsql_check() does such a great job of scanning EXECUTE.
Would there be any way to somehow flag some internal function to get that same treatment?

I am guessing "no"...
But thought it was worth the ask...

Thanks!

**Comment by okbob** [comment]
No, there is nothing for this purpose, and I have not any idea how to design it well.
