### ISSUE TITLE
Table pragma not working with tab chars

### ISSUE THREAD

**Issue by awn70** [okbob/plpgsql_check#167]
Hi,
I try to use the table pragma to create a temporary table. There seems to be a problem when the pragma code contains a tab char:

```perform plpgsql_check_pragma( 'table: my_tmp( id bigint, <tab>partno varchar(21) )' );```

With the tab char the temporary table is not present and I get an error:
relation "my_tmp" does not exist

Regards
Andreas

**Comment by okbob** [comment]
pá 5. 1. 2024 v 15:39 odesílatel awn70 ***@***.***> napsal:

> Hi,
> I try to use the table pragma to create a temporary table. There seems to
> be a problem when the pragma code contains a tab char:
>
> perform plpgsql_check_pragma( 'table: my_tmp( id bigint, <tab>partno
> varchar(21) )' );
>
> With the tab char the temporary table is not present and I get an error:
> relation "my_tmp" does not exist
>
This commit 5671953c9b8c9cf108f22644784dbbfdabbd144d should fix it.

Please check.

Regards

**Comment by awn70** [comment]
Ok, works now.
Thank you
