### ISSUE TITLE
Segmentation fault on plpgsql_check_function(oid)

### ISSUE THREAD

**Issue by casparsch** [okbob/plpgsql_check#168]
On postgres 14
> To be more exact: `select version()` gives me:
> `PostgreSQL 14.11 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), 64-bit`
> 

When I execute following sql-statement:
```
WITH
    prep as
    (
    SELECT  oid::regproc::text fq_pro_name
    ,       *
    FROM    pg_proc
    WHERE   prolang =
            (
            SELECT  oid
            FROM    pg_language
            WHERE   lanname = 'plpgsql'
            )
    AND     oid NOT IN
            (
            SELECT  tgfoid
            FROM    pg_trigger
            )
    )
SELECT  *
FROM    prep
JOIN    LATERAL
        (
        SELECT  *
        FROM    public.plpgsql_check_function(prep.oid)
        )   x
        ON TRUE
;
```
... it leads to a segmentation-fault (in the log)
**`2024-03-11 14:12:02.028 CET [27630] LOG:  server process (PID 31228) was terminated by signal 11: Segmentation fault`**

The same statement on postgres 15 and 16 went without any issues.
For all these database versions, the latest (packaged) available version of plpgsql_check are installed:
```
plpgsql_check_14.x86_64                                                                  2.7.2-1PGDG.rhel9                              @pgdg14
plpgsql_check_15.x86_64                                                                  2.7.2-1PGDG.rhel9                              @pgdg15
plpgsql_check_16.x86_64                                                                  2.7.2-1PGDG.rhel9                              @pgdg16
```
I saw you already released a newer version (2.7.3) but this is not yet available (for me).

Further details of my system, on the command: `cat /etc/os-release | grep PRETTY_NAME` gives me:
`PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"`

**Comment by okbob** [comment]
It can be bug in plpgsql_check, but unfortunately from this description I am not able to reproduce it. I need to see source code of some plpgsql function that crashes plpgsql_check.

please use function
```
postgres=# create or replace function wrap(o oid)
returns setof text as $$
begin
  raise notice '%', o::regprocedure;
  return query select * from plpgsql_check_function(o);
end;
$$ language plpgsql;
```
and your modified query
```
WITH
    prep as
    (
    SELECT  oid::regproc::text fq_pro_name
    ,       *
    FROM    pg_proc
    WHERE   prolang =
            (
            SELECT  oid
            FROM    pg_language
            WHERE   lanname = 'plpgsql'
            )
    AND     oid NOT IN
            (
            SELECT  tgfoid
            FROM    pg_trigger
            )
    )
SELECT  *
FROM    prep
JOIN    LATERAL
        (
        SELECT  *
        FROM    wrap(prep.oid)
        )   x
        ON TRUE
;
```
Then you will see names of checked function (on debug function). Last displayed forces crash. I need source code of this function.

**Comment by casparsch** [comment]
As required created the additional `wrap`-function
and executed the statement with that `plpgsql_check_function(...)` replaced `wrap(...)`
Last relevant lines (including the trail of the WITH-statement) from psql are:
```
...
SELECT  *
FROM    prep
JOIN    LATERAL
        (
        SELECT  *
        FROM    wrap(prep.oid)
        )   x
        ON TRUE
;
NOTICE:  oracle.translate_oracle_modifiers(text,boolean)
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```
That specific function: `oracle.translate_oracle_modifiers(text,boolean)` coming from extension `orafce`, should be familiar to you.

Hope this helps.

**Comment by okbob** [comment]
po 11. 3. 2024 v 15:59 odesílatel casparsch ***@***.***>
napsal:

> As required created the additional wrap-function
> and executed the statement with that plpgsql_check_function(...) replaced
> wrap(...)
> Last relevant lines (including the trail of the WITH-statement) from psql
> are:
>
> ...
> SELECT  *
> FROM    prep
> JOIN    LATERAL
>         (
>         SELECT  *
>         FROM    wrap(prep.oid)
>         )   x
>         ON TRUE
> ;
> NOTICE:  oracle.translate_oracle_modifiers(text,boolean)
> server closed the connection unexpectedly
> 	This probably means the server terminated abnormally
> 	before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.
> The connection to the server was lost. Attempting reset: Failed.
> !?>
>
> That specific function: oracle.translate_oracle_modifiers(text,boolean)
> coming from extension orafce, should be familiar to you.
>
Unfortunately, 2.7.2 crash on bugs related to wrapping (to using wrap
function).

please, try to use `load 'plpgsql_check';` before query execution

It should to fix the bug in 2.7.2 (related to use wrapping)

and run the query again

**Comment by okbob** [comment]
please, can you check 2.7.4?

**Comment by casparsch** [comment]
Accidentally reopened so close again

**Comment by okbob** [comment]
thank you for check

čt 21. 3. 2024 v 8:16 odesílatel casparsch ***@***.***>
napsal:
