### ISSUE TITLE
Segementation fault in plpgsql_check_function

### ISSUE THREAD

**Issue by kai-eckert** [okbob/plpgsql_check#169]
[crash.gz](https://github.com/okbob/plpgsql_check/files/14570003/crash.gz)

After importing attached database dump the following statement will cause a crash with segmentation fault in  postgresql 16.

`select array_to_string(array_agg(cf), e'\n')  from plpgsql_check_function('extra_long_schema_to_make_checker_fail.p_fill_ml_ticket_exch_crash', 0, 'text', false, false, false, false) cf;
`

When executing the statement:

` select array_to_string(array_agg(cf), e'\n')  from plpgsql_check_function('extra_long_schema_to_make_checker_fail.p_fill_ml_ticket_exch_ok', 0, 'text', false, false, false, false) cf; `

we do not get a crash and the only difference is that in the select into is one less column selected.

Used version of postgresql :

`crash=> select version();`
 `PostgreSQL 16.2 (Ubuntu 16.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit`

**Comment by okbob** [comment]
should be fixed by abbfe6498b290cd3d9cef5d66d2e5a95dbf5c1c8 
please check

**Comment by kai-eckert** [comment]
Now it works like a charm
:1st_place_medal: 

Thanks for the immediate fix.

As we use this in an internal project it would be nice if you can make a new official release as soon as possible.

**Comment by okbob** [comment]
2.7.4 is out now
