### ISSUE TITLE
false "record ... is not assigned yet" when fetch from cursor

### ISSUE THREAD

**Issue by proekt111** [okbob/plpgsql_check#17]
declare
  m_TargetRef      refcursor := null;
  m_TargetRec      record;
begin
    m_TargetRef := my_func (/* cursor returning function*/);
    fetch m_TargetRef into m_TargetRec; -- plpgsql_check force error at this point

**Comment by okbob** [comment]
I am checking it, and I don't see any wrong in this place. Probably "record is not assigned" will be detected early in next lines. I afraid,  plpgsql_check should not to process this pattern (I'll add it to limits). plpgsql_check does only local check - and it cannot to work with dynamic structures created out of function (like temp tables or refcursors). These structures doesn't exists in checking time, and this fact breaks any static analyse. You have to disable plpgsql_check for any functions, where refcursors are used or you have to explicitly specify expected datatype (don't use *record* there) - minimally for the check.
