### ISSUE TITLE
Release 2.7.12 on PGXN?

### ISSUE THREAD

**Issue by theory** [okbob/plpgsql_check#182]
Looks like 2.7.12 was never published on PGXN. 2.7.11 is the latest [there](https://pgxn.org/dist/plpgsql_check/).

Consider adding a GitHub workflow to auto publish, similar to [this one](/adjust/pg-base62/pull/8/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34).

**Comment by okbob** [comment]
Hi

there are not significant changes - major changes are related to support
meson

But supporting the GitHub workflow is good idea, I'll try it.

Regards

Pavel

čt 19. 12. 2024 v 21:09 odesílatel David E. Wheeler <
***@***.***> napsal:

**Comment by okbob** [comment]
I tested it and I did new release

**Comment by theory** [comment]
Nice!

**Comment by okbob** [comment]
pá 20. 12. 2024 v 18:04 odesílatel David E. Wheeler <
***@***.***> napsal:

Thank you for tip

Pavel
