### ISSUE TITLE
compile error when usee on postgres master branch

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#183]
not really urgent, as not based on productive code, just to notify

I get a compile error when used on postgres master branch since 21.12.2024
#11 0.827 In file included from src/assign.c:12:
#11 0.827 src/assign.c: In function ‘plpgsql_check_target’:
#11 0.827 src/plpgsql_check.h:541:45: error: ‘struct TupleDescData’ has no member named ‘attrs’
... 

it seems commit 5983a4cffc on postgres master branch changed TupleDescData

**Comment by okbob** [comment]
should be fixed now

**Comment by neiaberau** [comment]
that was fast, thanks a lot, all working again
