### ISSUE TITLE
Declared & used cursor reported as unused variable

### ISSUE THREAD

**Issue by shuehner** [okbob/plpgsql_check#19]
I am seeing this warning:
unused variable "cur_orderline"  in one of our pl functions in which we have the following:

    DECLARE Cur_OrderLine CURSOR (Order_ID VARCHAR)  FOR
      SELECT * .... ;
   ptr_ol RECORD; --OBTG:Cur_OrderLine--

then later:

    OPEN Cur_OrderLine(Cur_Order.C_Order_ID) ;
    Cur_OrderLine_ISOPEN:=true;
    FETCH Cur_OrderLine INTO ptr_ol;

Reporting here as a false positive as not clear to me if that is one of the known limits or a real issue.

Full function can be seen here:
https://gist.github.com/shuehner/46c1b8aaadbd687cdcd8

Interesting parts are:
https://gist.github.com/shuehner/46c1b8aaadbd687cdcd8#file-c_invoice_create-sql-L102
https://gist.github.com/shuehner/46c1b8aaadbd687cdcd8#file-c_invoice_create-sql-L387

**Comment by okbob** [comment]
It is plpgsql_bug - cursors are declared as variables, but aren't used in same context,

**Comment by okbob** [comment]
Should be fixed now
