### ISSUE TITLE
Feature request: check trigger definition (i.e. on insert)  vs. if TG_OP <> 'INSERT'

### ISSUE THREAD

**Issue by shuehner** [okbob/plpgsql_check#20]
Hello,
just an idea for a new performance related check.
Not sure if that is possible at all in full or in part here or easy.

Case:
trigger defined on a table as:
aprm_fin_finacc_tran_check_trg BEFORE INSERT OR DELETE OR UPDATE ON fin_finacc_transaction FOR EACH ROW EXECUTE PROCEDURE aprm_fin_finacc_tran_check_trg()

and then inside the trigger pl function:
IF (TG_OP = 'UPDATE') THEN
  do something
END IF;
IF(TG_OP = 'DELETE') THEN
  do something else
END IF;

So essentially for case 'INSERT' no reachable code.

So marking it as 'on insert' also is not useful as it contains no reachable code for this.

Is that something which could be added as special cases for validating trigger functions?

**Comment by okbob** [comment]
Your proposal is pretty complex :( - currently I have not support for identification of dead code, and for your proposal I need level higher heuristic.
