### ISSUE TITLE
Incorrect error generated while checking stable functions

### ISSUE THREAD

**Issue by m7onov** [okbob/plpgsql_check#24]
Is it a bug to receive message about exception that might not be raised? Below is example:
```
create or replace function test0() returns text 
language plpgsql
STABLE
as
$$
declare
begin
  if (extract(second from clock_timestamp())::integer % 2) = 1 then
    return 'OK';
  end if;
  raise exception 'TEST-EXCEPTION';
end;
$$;
```
```
create or replace function test() returns void as
$$
declare
  vstr text;
begin
  select 'test'
    into vstr
    from pg_catalog.pg_class
   where relname = test0();
end;
$$ language plpgsql;
```
Then if we execute 
`select plpgsql_check_function('test()'); `

we may (not always) receive message like:
```
postgres=# select plpgsql_check_function('test()');
               plpgsql_check_function               
----------------------------------------------------
 error:P0001:5:SQL statement:TEST-EXCEPTION
 Context: PL/pgSQL function test0() line 7 at RAISE
(2 rows)
```
Which I suppose is not correct. Note that in test0() function "STABLE" keyword does the trick. Without it no error message received

**Comment by okbob** [comment]
It is not a bug, but feature :( - based on design of PostgreSQL planner - any expression in plpgsql is translated to SQL, and later translated to PostgreSQL query execution plan. Planner try to replace functions calls by constants and then it eval function test0. PLpgSQL needs to execution plans for some checks - so starts planner, and when planner fails, then plpgsql_check show this error.

     /*
      * Ordinarily we are only allowed to simplify immutable functions. But for
      * purposes of estimation, we consider it okay to simplify functions that   
      * are merely stable; the risk that the result might change from planning
      * time to execution time is worth taking in preference to not being able
      * to estimate the value at all.
      */
     if (funcform->provolatile == PROVOLATILE_IMMUTABLE)
               /* okay */ ;  
     else if (context->estimate && funcform->provolatile == PROVOLATILE_STABLE   
               /* okay */ ;
     else
             return NULL;

I am sorry I cannot to fix it.
