### ISSUE TITLE
Install on 9.6.3

### ISSUE THREAD

**Issue by sttachoires** [okbob/plpgsql_check#25]
Hi,

I just discover this extension, and I want to install it on demand.
So I followed the procedure, and I want to automate it
When I do the make && make install, all ok
When I load extension into a database and create it, all ok
But when I try to shared_preload_libraries it...
`PG-XX000 FATAL:  could not load library "/tech/postgres/9.6.3/server/lib/plpgsql_check.so": /tech/postgres/9.6.3/server/lib/plpgsql_check.so: undefined symbol: plpgsql_parser_setup`

This extension cannot be preloaded?

**Comment by okbob** [comment]
2017-06-02 10:34 GMT+02:00 Stephane Tachoires <notifications@github.com>:

> Hi,
>
> I just discover this extension, and I want to install it on demand.
> So I followed the procedure, and I want to automate it
> When I do the make && make install, all ok
> When I load extension into a database and create it, all ok
> But when I try to shared_preload_libraries it...
> PG-XX000 FATAL: could not load library "/tech/postgres/9.6.3/server/lib/plpgsql_check.so":
> /tech/postgres/9.6.3/server/lib/plpgsql_check.so: undefined symbol:
> plpgsql_parser_setup
>
> This extension cannot be preloaded?
>

This case was not tested - it requires plpgsql engine be loaded first. Try
to load plpgsql before plpgsql_check in shared_preload_libraries.

Regards

Pavel

**Comment by sttachoires** [comment]
Yes, that's what i've done.
And then it works :)
Thanks.
