### ISSUE TITLE
windows binaries fro PG10

### ISSUE THREAD

**Issue by zam6ak** [okbob/plpgsql_check#27]
Any chance to get windows binaries for PG10 beta4?

**Comment by okbob** [comment]
2017-09-19 1:04 GMT+02:00 zam6ak <notifications@github.com>:

> Any chance to get windows binaries for PG10 beta4?
>
not from me. I have not time to build it - I have not a windows, and I
don't plan to install it early. I have to finish some projects before and
clean desk.

**Comment by okbob** [comment]
please check https://postgres.cz/files/plpgsql_check-1.2.2-1-mswin.zip
