### ISSUE TITLE
Feature Request: Detect variable that is never read from 

### ISSUE THREAD

**Issue by zgrannan** [okbob/plpgsql_check#28]
For example, consider the following function:
```plpgsql
CREATE FUNCTION a() RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
 foo int;
BEGIN
  foo := 2;
  RETURN 1;
END
$$;
```

In the above function, the variable `foo` is assigned a value but it is never read from. I think this would always indicate a mistake when writing the function, since the variable could just be omitted. Would it be possible to add a check for this condition?

**Comment by okbob** [comment]
should be done

**Comment by zgrannan** [comment]
Works great! Thanks a lot
