### ISSUE TITLE
PL/pgsql variable type check against table column type

### ISSUE THREAD

**Issue by RealEnder** [okbob/plpgsql_check#32]
In a lot code reviews I often catch wrong variable type declarations, which leads to severe performance degradation.
Some synthetic example:
```
DECLARE
  vID NUMERIC(19,0) := 0;

<snip>

SELECT * FROM some_large_table WHERE id=vID;
```
In `some_large_table` the `id` is declared as BIGINT, but `vID` is NUMERIC(19,0), thus PostgreSQL does implicit cast and slows down in time.
So can we detect such situations?

**Comment by okbob** [comment]
2018-03-20 7:20 GMT+01:00 Alex Stanev <notifications@github.com>:

> In a lot code reviews I often catch wrong variable type declarations,
> which leads to severe performance degradation.
> Some synthetic example:
>
> DECLARE
>   vID NUMERIC(19,0) := 0;
>
> <snip>
>
> SELECT * FROM some_large_table WHERE id=vID;
>
> In some_large_table the id is declared as BIGINT, but vID is
> NUMERIC(19,0), thus PostgreSQL does implicit cast and slows down in time.
> So can we detect such situations?
>
Theoretically we can, but it is not easy work. You need to iterate over
execution plan and search implicit casts related to parameter.
Unfortunately this cast can be far from parameter, so this check can be
blind in some cases. I am not sure if is there necessary infrastructure.
Maybe some for explain allows iteration over query plan. This is fully
outside plpgsql engine.

**Comment by RealEnder** [comment]
Those issues are generally easy to spot.
How about issuing a notice for user defined variables, that are used in DML operations(tricky part is to detect those), but their type is not defined like table.column%TYPE or table%ROWTYPE? Of course, using eg. int8 is fully acceptable, but allows for bad practices and regressions when code evolves in time.

**Comment by okbob** [comment]
2018-03-20 8:19 GMT+01:00 Alex Stanev <notifications@github.com>:

> Those issues are generally easy to spot.
> How about issuing a notice for user defined variables, that are used in
> DML operations(tricky part is to detect those), but their type is not
> defined like table.column%TYPE or table%ROWTYPE? Of course, using eg. int8
> is fully acceptable, but allows for bad practices and regressions when code
> evolves in time.
>
It is probably much harder than first request, if it is not impossible.
%ROWTYPE is used in parser stage - and transformed to normal data
information - the information about relation to some database object is
lost there.

It should be detected inside query - you should to search filter, where
some key is casted and compared with some constant.

**Comment by okbob** [comment]
I wrote a test that try to identify some symptoms of this issue 68b899e30f4dd2658d01135b264bba6e7202235b Please check it. Currently it is tested only on PostgreSQL 11. Tomorrow I'll port on other supported releases.

**Comment by RealEnder** [comment]
10x, will try to test it. I already did manual review and fix for the system I identified the issue, but I'm sure we still have a lot of these to emerge elsewhere. Will have to wait for the backport.

**Comment by okbob** [comment]
I checked it against 10.4.

**Comment by okbob** [comment]
please, can you recheck last commit?

**Comment by RealEnder** [comment]
Tested on 10.3 and works as described in docs. Noticed, that for some performance issues we don't have the Query: part and if we have some big query, joining several tables and using several variables, we end with something like this as result:
```
performance:42804:97:SQL statement:target type is different type than source type
Detail: cast "text" value to "character varying" type
Hint: Hidden casting can be a performance issue.
performance:42804:97:SQL statement:target type is different type than source type
Detail: cast "text" value to "character varying" type
Hint: Hidden casting can be a performance issue.
performance:42804:97:SQL statement:target type is different type than source type
Detail: cast "text" value to "character varying" type
Hint: Hidden casting can be a performance issue.
```

**Comment by okbob** [comment]
2018-06-11 15:55 GMT+02:00 Alex Stanev <notifications@github.com>:

> Tested on 10.3 and works as described in docs. Noticed, that for some
> performance issues we don't have the Query: part and if we have some big
> query, joining several tables and using several variables, we end with
> something like this as result:
>
> performance:42804:97:SQL statement:target type is different type than source type
> Detail: cast "text" value to "character varying" type
> Hint: Hidden casting can be a performance issue.
> performance:42804:97:SQL statement:target type is different type than source type
> Detail: cast "text" value to "character varying" type
> Hint: Hidden casting can be a performance issue.
> performance:42804:97:SQL statement:target type is different type than source type
> Detail: cast "text" value to "character varying" type
> Hint: Hidden casting can be a performance issue.
>
>
please, can me send test case? possibly to private mail
pavel.stehule@gmail.com

I cannot to fix it without test case.

**Comment by RealEnder** [comment]
Will try to cut down minimal test case for that, tried it against rather large project.

**Comment by RealEnder** [comment]
Sorry, I can't reproduce it. If this is release stopper, please go ahead. Will give it another try when I have more time for it.

**Comment by okbob** [comment]
2018-06-24 14:36 GMT+02:00 Alex Stanev <notifications@github.com>:

> Sorry, I can't reproduce it. If this is release stopper, please go ahead.
> Will give it another try when I have more time for it.
>

no problem

Pavel
