### ISSUE TITLE
set, case

### ISSUE THREAD

**Issue by parihaaraka** [okbob/plpgsql_check#34]
ubuntu 18.04, pg 11, *latest* plpgsql_check from git
`set local search_path to public, test;` -> error:XX000:3:SET:unrecognized cmd_type:27
`case my_var  .. end case;` -> warning:00000:3:DECLARE:unused variable "my_var"

**Comment by okbob** [comment]
Should be fixed now, please check. Thank you for report.

**Comment by parihaaraka** [comment]
Yep, it's ok now. Thank you!
