### ISSUE TITLE
Readme - ICU dependency

### ISSUE THREAD

**Issue by aleszeleny** [okbob/plpgsql_check#37]
Consider adding dependency on to build the extension. At least for Ububtu/Xeniall I had to install `libicu-dev`.
Something like `sudo apt install libicu-dev`  might be added into readme.

**Comment by okbob** [comment]
plpgsql_check doesn't require ICU.  There is some issue in PostgreSQL extension building environment to require libicu-dev, when Postgres was compiled with libicu support.  The dependency on libicu was mentioned in README, but only for WIN. Maybe there are missing dependency to libicu in postgresql-dev package.  I pushed your node to README

**Comment by okbob** [comment]
4990f7d492be49996e7e68231fc3b23dfe653f74
