### ISSUE TITLE
postgresql 11,call procedure commit,show error

### ISSUE THREAD

**Issue by lvbuwei** [okbob/plpgsql_check#42]
create table t1(a int);
create or replace  PROCEDURE test1() as
 $$
 begin
 insert into t1 values(1);
commit;
insert into t1 values(2);
rollback;
end;
$$language plpgsql;
call test1();
select * from plpgsql_check_function('test1()');
                plpgsql_check_function             
 error:2D000:1:COMMIT:invalid transaction termination
(1 row)

**Comment by okbob** [comment]
Should be fixed now.

**Comment by okbob** [comment]
Thank you for report

so 12. 1. 2019 v 3:25 odesílatel lvbuwei <notifications@github.com> napsal:
