### ISSUE TITLE
manage transition tables in triggers

### ISSUE THREAD

**Issue by marco44** [okbob/plpgsql_check#44]
We're starting to have triggers declared with ```REFERENCING NEW TABLE AS``` for which plpgsql_check returns ```relation "xxxx" does not exist``` errors.

Maybe these names could be passed to the check fuctions, as they are available from pg_trigger ?

Regards

**Comment by okbob** [comment]
Currently transition tables are not supported by plpgsql check. I hope so I fix it in next days.

**Comment by marco44** [comment]
Great news !

**Comment by okbob** [comment]
please check 1.7 branch

**Comment by marco44** [comment]
Hi, I add some minor issues with the code (the function prototype wasn't adjusted everywhere, I did a PR with what I had to fix… I only tested with the plpgsql_check_function_tb, but with this function it works

**Comment by okbob** [comment]
transition tables are supported by 1.7 release - it is at master now.

**Comment by marco44** [comment]
Thanks a lot !
