### ISSUE TITLE
Potential issues with 1.7 release - change in signature for entrypoint functions

### ISSUE THREAD

**Issue by jacobdr** [okbob/plpgsql_check#47]
I know that today was release day, but code I had running this morning doesn't seem to be working now. So perhaps a smell? 

Anyway, ripping straight from the [README](https://github.com/okbob/plpgsql_check#mass-check), the following code is no longer working for me:

```sql
 SELECT p.oid, p.proname, plpgsql_check_function(p.oid)
   FROM pg_catalog.pg_namespace n
   JOIN pg_catalog.pg_proc p ON pronamespace = n.oid
   JOIN pg_catalog.pg_language l ON p.prolang = l.oid
  WHERE l.lanname = 'plpgsql' AND p.prorettype <> 2279;
```

Error message is: 
```
SQL Error [XX000]: ERROR: unexpected number of parameters, you should to update extension
  Where: PL/pgSQL function plpgsql_check_function(regprocedure,regclass,text,boolean,boolean,boolean,boolean) line 3 at RETURN QUERY
```

I am on PG 11.2 I think, OS is Ubuntu 18

I am brand new to this project (literally installed for the first time this morning), so I don't think I can be of any real help in making a patch. But do let me know if you need any further output to help aid in debugging.

**Comment by jacobdr** [comment]
Here's how I built it: 

```Dockerfile
RUN git clone https://github.com/okbob/plpgsql_check.git /tmp/plpgsql_check && \
    cd /tmp/plpgsql_check && \
    make USE_PGXS=1 clean && \
    make USE_PGXS=1 all && \
    make USE_PGXS=1 install
```

**Comment by jacobdr** [comment]
Checkout and re-install from 4e53098c77c46028c969b6656212846337977305 seems to fix the issue for me

**Comment by okbob** [comment]
čt 18. 4. 2019 v 2:36 odesílatel Jacob Roberts <notifications@github.com>
napsal:

> I know that today was release day, but code I had running this morning
> doesn't seem to be working now. So perhaps a smell?
>
> Anyway, ripping straight from the README
> <https://github.com/okbob/plpgsql_check#mass-check>, the following code
> is no longer working for me:
>
>  SELECT p.oid, p.proname, plpgsql_check_function(p.oid)
>    FROM pg_catalog.pg_namespace n
>    JOIN pg_catalog.pg_proc p ON pronamespace = n.oid
>    JOIN pg_catalog.pg_language l ON p.prolang = l.oid
>   WHERE l.lanname = 'plpgsql' AND p.prorettype <> 2279;
>
> Error message is:
>
> SQL Error [XX000]: ERROR: unexpected number of parameters, you should to update extension
>   Where: PL/pgSQL function plpgsql_check_function(regprocedure,regclass,text,boolean,boolean,boolean,boolean) line 3 at RETURN QUERY
>
> if you had some older version installed, then this is correct behave. You
had to drop some older releases, and install new.

please try

drop extension plpgsql_check;
create extension plpgsql_check;

**Comment by okbob** [comment]
čt 18. 4. 2019 v 3:59 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> čt 18. 4. 2019 v 2:36 odesílatel Jacob Roberts <notifications@github.com>
> napsal:
>
>> I know that today was release day, but code I had running this morning
>> doesn't seem to be working now. So perhaps a smell?
>>
>> Anyway, ripping straight from the README
>> <https://github.com/okbob/plpgsql_check#mass-check>, the following code
>> is no longer working for me:
>>
>>  SELECT p.oid, p.proname, plpgsql_check_function(p.oid)
>>    FROM pg_catalog.pg_namespace n
>>    JOIN pg_catalog.pg_proc p ON pronamespace = n.oid
>>    JOIN pg_catalog.pg_language l ON p.prolang = l.oid
>>   WHERE l.lanname = 'plpgsql' AND p.prorettype <> 2279;
>>
>> Error message is:
>>
>> SQL Error [XX000]: ERROR: unexpected number of parameters, you should to update extension
>>   Where: PL/pgSQL function plpgsql_check_function(regprocedure,regclass,text,boolean,boolean,boolean,boolean) line 3 at RETURN QUERY
>>
>> if you had some older version installed, then this is correct behave. You
> had to drop some older releases, and install new.
>
> please try
>
> drop extension plpgsql_check;
> create extension plpgsql_check;
>

and before compilation

git fetch
git pull
make clean
make all
make install

Maybe it was badly compiled. The default ignore dependency

**Comment by okbob** [comment]
please, recheck

**Comment by jacobdr** [comment]
Thanks for this. I will reopen if the issue fears its head again.

JR
