### ISSUE TITLE
Enhancement for style liniting

### ISSUE THREAD

**Issue by palmerj** [okbob/plpgsql_check#48]
Do you think this tools could be enhance for style linting as well? e.g:

1.  Keywords are written uppercase, names are written in lowercase.
2. 4 space indention.
3. One command per line.
4.  Keywords LOOP, ELSE, ELSIF, END IF, WHEN on a new line.
5.  Commas in front/end of separated elements.
6. Call parameters aligned, operators aligned, values aligned.
7.  SQL keywords are either indent, or right aligned within a SQL command.
8. Within a function only single line comments `--` are used.
9. Brackets are used when needed or when helpful to clarify a construct.
10. common variable naming conventions

**Comment by okbob** [comment]
It is much more easy to produce well formatted code from AST than check format. I though more times about it, but I am not sure if this should be part of plpgsql_check or some other feature - more, some informations are not available - I know line and start of almost all keywords, but I don't know if keyword was written in uppercase or lowercase (although probably I am able to get this info (but not directly). But I had not any information about aux keywords like END IF, .. 

So with plpgsql parser, that is used as foundation of plpgsql_check I can do some points from your list and lot of not. So for style check is probably better to write own parser (based on source code of plpgsql parser), and it mean some new extension. More semantic and style analyses are too different, and there are not a reason why to have one superbig extension instead two.

Some extension of this kind can be nice. I think so can be joined with SQL formatter, and style linter (and plpgsql formatter). I have not time on this task (but I can help with some work if you will start and do it). I spent lot of time with maintaining plpgsql_check and pspg, and I would not to start other bigger project.

**Comment by palmerj** [comment]
HI @okbob thank you for your excellent reply. Your description of the problem makes sense. If I have some time I would love to create a new tool. Do you think it would need to be an extension or could it be a stand alone formatting tool that doesn't need PG installed?

**Comment by okbob** [comment]
Can be nice, if this will be a postgres extension (in C langue) due simple deployment and great accessibility. But for this purpose (when you check just style or reformat), you don't need strong and direct access to Postgres catalogue - so you can use any technology that you want.

**Comment by kwargs** [comment]
Hi @palmerj. You may be interesting in https://github.com/lelit/pglast. 
It has `SQL` formatter, but with limited `PLpgSQL` support - https://gist.github.com/kwargs/2f3649f7e28e2b360a151f47ef726f07

**Comment by palmerj** [comment]
Thanks @kwargs. I had too many problems with pglast. Note I've now found https://github.com/darold/pgFormatter which seems to be very good including with PgSQL. It still have a few bugs, so I've submitted those.
