### ISSUE TITLE
Create temp table and use in plpgsql function

### ISSUE THREAD

**Issue by topharley** [okbob/plpgsql_check#51]
Hi!

I have function
```
create or replace function import$test() returns void as $body$
begin

    CREATE TEMPORARY TABLE tmp(
      list varchar(50)
    ) ON COMMIT DROP;

    insert into tmp(list) select 'ABC' ;
   
   --use data in tmp

end;
$body$
LANGUAGE PLPGSQL;
```

I plpgsql_check prints error:
import$test: error:42P01:8:SQL statement:relation "tmp" does not exist

How i can override this behavior ?

**Comment by okbob** [comment]
Hi

pá 4. 10. 2019 v 12:28 odesílatel topharley <notifications@github.com>
napsal:

> Hi!
>
> I have function
>
> create or replace function import$test() returns void as $body$
> begin
>
>     CREATE TEMPORARY TABLE tmp(
>       list varchar(50)
>     ) ON COMMIT DROP;
>
>     insert into tmp(list) select 'ABC' ;
>
>    --use data in tmp
>
> end;
> $body$
> LANGUAGE PLPGSQL;
>
> I plpgsql_check prints error:
> import$test: error:42P01:8:SQL statement:relation "tmp" does not exist
>
> How i can override this behavior ?
>

It's known limit of  plpgsql_check, that does only static analyze. You can
just disable plpgsql_check for this function, and that it all what is
possible.

Regards

Pavel
