### ISSUE TITLE
unused variable forloops

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [okbob/plpgsql_check#53]
this function:

```sql
 CREATE OR REPLACE FUNCTION reverse(text) RETURNS text AS $$
    DECLARE
    original alias for $1;
          reverse_str text;
          i int4;
    BEGIN
        IF original IS NULL THEN
            RETURN null;
        END IF;
        reverse_str := '';
        FOR i IN REVERSE LENGTH(original)..1 LOOP
          reverse_str := reverse_str || substr(original,i,1);
        END LOOP;
    RETURN reverse_str;
    END;$$
    LANGUAGE plpgsql IMMUTABLE;
```

returns `unused variable "i"` for me.

**Comment by okbob** [comment]
It is correct. Control variable of `FOR` cycle is automaticly  defined just for cycle's body. Your variable i is shadowed by this automatic variable.

**Comment by verfriemelt-dot-org** [comment]
wow, okay. i never knew!

usually i have the case with records, and they are not automatically defined:

```sql
DO $$
BEGIN

  FOR r IN ( select * from abk ) LOOP
    raise notice '%', r;
  END LOOP;

END $$;
```
`Query failed: ERROR:  loop variable of loop over rows must be a record or row variable or list of scalar variables`

thank you for your quick response!

**Comment by okbob** [comment]
út 12. 11. 2019 v 16:29 odesílatel ಠ_ಠ <notifications@github.com> napsal:

> wow, okay. i never knew!
>
> usually i have the case with records, and they are not automatically
> defined:
>
> DO $$BEGIN
>
>   FOR r IN ( select * from abk ) LOOP
>     raise notice '%', r;
>   END LOOP;
>
> END $$;
>
> Query failed: ERROR: loop variable of loop over rows must be a record or
> row variable or list of scalar variables
>
> thank you for your quick response!
>

it is different case and source of incompatibility with oracle pl/sql.
