### ISSUE TITLE
License clarification (LICENSE vs. README.md)

### ISSUE THREAD

**Issue by shuehner** [okbob/plpgsql_check#54]
Hello,
while working on packaging your extension for Debian/Ubuntu i noticed some inconsistency for the written copyright/license.

In concrete:
LICENSE file contained in the repo is kind of short
README.md file (License section) is more extensive with copyright.

I assume the README.md section would be the more appropriate text when to talk about license/copyright of your extension?

For the moment i used this:
https://salsa.debian.org/postgresql/plpgsql-check/blob/master/debian/copyright

Could you please check is that is appropriate and maybe update the LICENSE file (if needed)?

Thanks,
Stefan

**Comment by okbob** [comment]
Hi

po 9. 12. 2019 v 15:54 odesílatel Stefan Hühner <notifications@github.com>
napsal:

> Hello,
> while working on packaging your extension for Debian/Ubuntu i noticed some
> inconsistency for the written copyright/license.
>
I don't think so is necessary to be too strict about licence. plpgsql_check
uses primary BSD licence - this is text in README. It is important for
Debian or RedHat. Optionally it uses postcardware licence, but it has not
any legal power. It is +/- small joke.

In concrete:
> LICENSE file contained in the repo is kind of short
> README.md file (License section) is more extensive with copyright.
>
> I assume the README.md section would be the more appropriate text when to
> talk about license/copyright of your extension?
>
Two important point from LICENCE

"If you like it - send a postcard to address:" -- it is optional

"Use this code freely on own risk" -- it is in conformance with BSD or
public domain licence. So although it is different text, I don't see
conflict.

Regards

p.s. Thank you for your work


Pavel

**Comment by okbob** [comment]
this issue should be fixed by last commit
