### ISSUE TITLE
Issue with table returning functions and return query execute

### ISSUE THREAD

**Issue by marco44** [okbob/plpgsql_check#57]
test=# create or replace function demo_pb (a int) returns table (foo int, bar int) language plpgsql
as
$$
begin
  return query select a,1;
end;
$$
;
CREATE FUNCTION
test=# select * from plpgsql_check_function_tb('public.demo_pb(int)'::regprocedure);
 functionid | lineno | statement | sqlstate | message | detail | hint | level | position | query | context 
------------+--------+-----------+----------+---------+--------+------+-------+----------+-------+---------
(0 rows)
test=# create or replace function demo_pb (a int) returns table (foo int, bar int) language plpgsql
as
$$
begin
  return query execute 'select ' || a || ',1';
end;
$$
;
CREATE FUNCTION
test=# select * from plpgsql_check_function_tb('public.demo_pb(int)'::regprocedure);
 functionid | lineno | statement | sqlstate |            message            | detail | hint |     level     | position | query | context 
------------+--------+-----------+----------+-------------------------------+--------+------+---------------+----------+-------+---------
 demo_pb    |      Ø | Ø         | 00000    | unmodified OUT variable "foo" | Ø      | Ø    | warning extra |        Ø | Ø     | Ø
 demo_pb    |      Ø | Ø         | 00000    | unmodified OUT variable "bar" | Ø      | Ø    | warning extra |        Ø | Ø     | Ø
(2 rows)

**Comment by PierreDucroquet** [comment]
It seems the fix is just:
```
diff --git a/src/stmtwalk.c b/src/stmtwalk.c
index d223f6b..b69bcec 100644
--- a/src/stmtwalk.c
+++ b/src/stmtwalk.c
@@ -1032,6 +1032,7 @@ plpgsql_check_stmt(PLpgSQL_checkstate *cstate, PLpgSQL_stmt *stmt, int *closing,
 #endif
 
                                                                                  stmt_rq->params);
+                                               cstate->found_return_query = true;
                                        }
                                }
                                break;
```

**Comment by okbob** [comment]
I am not sure if just set found_return_query is correct fix. In this case plpgsql_check cannot to detect number of columns of result. So some warning is correct, just the warning message should be better.

**Comment by okbob** [comment]
I changed to error message to form:
<pre>
postgres=# select * from plpgsql_check_function('demo_pb');
┌────────────────────────────────────────────────────────────┐
│                   plpgsql_check_function                   │
╞════════════════════════════════════════════════════════════╡
│ warning extra:00000:OUT variable "foo" is maybe unmodified │
│ Detail: cannot to determine result of dynamic SQL          │
│ warning extra:00000:OUT variable "bar" is maybe unmodified │
│ Detail: cannot to determine result of dynamic SQL          │
└────────────────────────────────────────────────────────────┘
(4 rows)
</pre>

It's question if in this case is better be more strict or more tolerant.

**Comment by marco44** [comment]
Yeah, that could do it. It can be ignored if it returns a specific result.

**Comment by marco44** [comment]
(or to say it another way, i'd rather ignore the error message myself today than missing it the day I want to use it :) )

**Comment by okbob** [comment]
But in this case plpgsql_check doesn't know if dynamic SQL returns 0, 1, or 2 columns result. I know nothing about dynamic SQL in static analyze time (when argument of EXECUTE statement is expression).

**Comment by okbob** [comment]
yes, I think so is better to be strict and in this case raise possible false alarm.

**Comment by marco44** [comment]
Thanks a lot. Do you have an idea when next release will be ? (to know if I have to build a package myself from git for our CI environment, or if the package will be available soon).

Regards

**Comment by okbob** [comment]
I released 1.9.1 two minutes ago

Pavel

but I don't know when Devrim refresh this package


po 27. 4. 2020 v 14:35 odesílatel Marc Cousin <notifications@github.com>
napsal:

**Comment by marco44** [comment]
Great news. I'm using Debian, so it's Christoph Berg I need :)

**Comment by marco44** [comment]
I just noticed, there is no PGDG package yet. This extension is so useful, shouldn't it be ?

**Comment by okbob** [comment]
po 27. 4. 2020 v 17:12 odesílatel Marc Cousin <notifications@github.com>
napsal:

> I just noticed, there is no PGDG package yet. This extension is so useful,
> shouldn't it be ?
>
I think so it is.

But maybe some is wrong

**Comment by marco44** [comment]
@df7cb I cannot find this package in PGDG's repository, should this be packaged ? Can I help somehow ?

**Comment by df7cb** [comment]
We are working on it, but it got stalled: https://salsa.debian.org/postgresql/plpgsql-check

Will try to ping the prospective maintainer.

**Comment by marco44** [comment]
Oh, great, thanks.

**Comment by okbob** [comment]
po 27. 4. 2020 v 17:12 odesílatel Marc Cousin <notifications@github.com>
napsal:

> I just noticed, there is no PGDG package yet. This extension is so useful,
> shouldn't it be ?
>
aha, I use fedora packages - and there is already. For debian it is missing.

Pavel
