### ISSUE TITLE
plpgsql_check_function other_warnings

### ISSUE THREAD

**Issue by marco44** [okbob/plpgsql_check#59]
This parameter is documented as other_warnings, but is declared as others_warnings in the function definition (which looks like a typo)

**Comment by okbob** [comment]
fixed, thank you for report.

**Comment by marco44** [comment]
Yeah, but "other" was the one that was gramatically correct. Others is a pronoun, what you need here is an adjective, which cannot be "others".

**Comment by okbob** [comment]
út 5. 5. 2020 v 8:13 odesílatel Marc Cousin <notifications@github.com>
napsal:

> Yeah, but "other" was the one that was gramatically correct. Others is a
> pronoun, what you need here is an adjective, which cannot be "others".
>
I know, but I cannot to change it without compatibility break :(

**Comment by okbob** [comment]
but on second hand plpgsql_check doesn't ensure back compatibility so this fix should not be problem. I renamed this argument
