### ISSUE TITLE
Work with psql (PostgreSQL) 12.2 & Windows 10

### ISSUE THREAD

**Issue by binu305** [okbob/plpgsql_check#60]
In any case can we get files compatible with PSQL 12.2 & Windows 10 ?
plpgsql_check.dll 
plpgsql_check.control
plpgsql_check--0.8.sql

Tried with available version(plpgsql_check-1.9.2). But not working

**Comment by okbob** [comment]
Hi

út 26. 5. 2020 v 10:29 odesílatel Binu V Pillai <notifications@github.com>
napsal:

> In any case can we get files compatible with PSQL 12.2 & Windows 10 ?
> plpgsql_check.dll
> plpgsql_check.control
> plpgsql_check--0.8.sql
>
> Tried with available version(plpgsql_check-1.9.2). But not working
>
you can install plpgsql_check from
http://okbob.blogspot.com/2019/10/dll-for-plpgsqlcheck-17-are-available.html

There is important rule for all postgres's extensions. Every extension is
compiled against Postgres major release. So you can use extension for
Postgres 10 only with Postgres 10, etc.

Regards

Pavel
