### ISSUE TITLE
Compile error on PostgreSQL docker container

### ISSUE THREAD

**Issue by asharabu** [okbob/plpgsql_check#61]
Hi,

I tried to compile plpqsql_check plugin in postgres docker container but showing below error, I tried on versions 11.8 and 12.3.

------
root@af98e78a8c04:/plpgsql_check# make install
gcc -Wextra -g -fPIC -I/usr/lib/postgresql/11/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o src/plpgsql_check.o src/plpgsql_check.c
In file included from src/plpgsql_check.c:26:0:
src/plpgsql_check.h:1:22: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
                      ^
compilation terminated.
<builtin>: recipe for target 'src/plpgsql_check.o' failed
make: *** [src/plpgsql_check.o] Error 1
----

Please, anyone, help me to integrate  plpgsql_check extension on Postgres docker container.

**Comment by okbob** [comment]
čt 28. 5. 2020 v 11:55 odesílatel asharabu <notifications@github.com>
napsal:

> Hi,
>
> I tried to compile plpqsql_check plugin in postgres docker container but
> showing below error, I tried on versions 11.8 and 12.3.
> ------------------------------
> root@af98e78a8c04:/plpgsql_check# make install
> gcc -Wextra -g -fPIC
> -I/usr/lib/postgresql/11/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src
> -Wall -I. -I./ -I/usr/include/postgresql/11/server
> -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2
> -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5 -c -o
> src/plpgsql_check.o src/plpgsql_check.c
> In file included from src/plpgsql_check.c:26:0:
> src/plpgsql_check.h:1:22: fatal error: postgres.h: No such file or
> directory
> #include "postgres.h"
> ^
> compilation terminated.
> : recipe for target 'src/plpgsql_check.o' failed
> make: *** [src/plpgsql_check.o] Error 1
>
> Please, anyone, help me to integrate plpgsql_check extension on Postgres
> docker container.
>

I don't know docker container - but it looks you miss postgres dev package
- or there is some issue in you environment.

can you run "pg_config"?

**Comment by asharabu** [comment]
Hi,
Please see the result,


> root@af98e78a8c04:/plpgsql_check# pg_config
BINDIR = /usr/lib/postgresql/11/bin
DOCDIR = /usr/share/doc/postgresql-doc-11
HTMLDIR = /usr/share/doc/postgresql-doc-11
INCLUDEDIR = /usr/include/postgresql
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/11/server
LIBDIR = /usr/lib/x86_64-linux-gnu
PKGLIBDIR = /usr/lib/postgresql/11/lib
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/postgresql/11/man
SHAREDIR = /usr/share/postgresql/11
SYSCONFDIR = /etc/postgresql-common
PGXS = /usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=/usr/include' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu' '--libexecdir=/usr/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' 'PYTHON=/usr/bin/python3' '--mandir=/usr/share/postgresql/11/man' '--docdir=/usr/share/doc/postgresql-doc-11' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/11' '--bindir=/usr/lib/postgresql/11/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--with-extra-version= (Debian 11.8-1.pgdg90+1)' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-llvm' 'LLVM_CONFIG=/usr/bin/llvm-config-6.0' 'CLANG=/usr/bin/clang-6.0' '--with-systemd' '--with-selinux' 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-z,relro -Wl,-z,now' '--with-gssapi' '--with-ldap' '--with-includes=/usr/include/mit-krb5' '--with-libs=/usr/lib/mit-krb5' '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5' 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
CC = gcc
CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include/mit-krb5
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm
VERSION = PostgreSQL 11.8 (Debian 11.8-1.pgdg90+1)

>

**Comment by okbob** [comment]
čt 28. 5. 2020 v 12:25 odesílatel asharabu <notifications@github.com>
napsal:

> Hi,
> Please see the result,
>
> root@af98e78a8c04:/plpgsql_check# pg_config
> BINDIR = /usr/lib/postgresql/11/bin
> DOCDIR = /usr/share/doc/postgresql-doc-11
> HTMLDIR = /usr/share/doc/postgresql-doc-11
> INCLUDEDIR = /usr/include/postgresql
> PKGINCLUDEDIR = /usr/include/postgresql
> INCLUDEDIR-SERVER = /usr/include/postgresql/11/server
> LIBDIR = /usr/lib/x86_64-linux-gnu
> PKGLIBDIR = /usr/lib/postgresql/11/lib
> LOCALEDIR = /usr/share/locale
> MANDIR = /usr/share/postgresql/11/man
> SHAREDIR = /usr/share/postgresql/11
> SYSCONFDIR = /etc/postgresql-common
> PGXS = /usr/lib/postgresql/11/lib/pgxs/src/makefiles/pgxs.mk
> CONFIGURE = '--build=x86_64-linux-gnu' '--prefix=/usr'
> '--includedir=/usr/include' '--mandir=/usr/share/man'
> '--infodir=/usr/share/info' '--sysconfdir=/etc' '--localstatedir=/var'
> '--disable-silent-rules' '--libdir=/usr/lib/x86_64-linux-gnu'
> '--libexecdir=/usr/lib/x86_64-linux-gnu' '--disable-maintainer-mode'
> '--disable-dependency-tracking' '--with-icu' '--with-tcl' '--with-perl'
> '--with-python' '--with-pam' '--with-openssl' '--with-libxml'
> '--with-libxslt' 'PYTHON=/usr/bin/python3'
> '--mandir=/usr/share/postgresql/11/man'
> '--docdir=/usr/share/doc/postgresql-doc-11'
> '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/'
> '--datadir=/usr/share/postgresql/11' '--bindir=/usr/lib/postgresql/11/bin'
> '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/'
> '--includedir=/usr/include/postgresql/' '--with-extra-version= (Debian
> 11.8-1.pgdg90+1)' '--enable-nls' '--enable-integer-datetimes'
> '--enable-thread-safety' '--enable-tap-tests' '--enable-debug'
> '--enable-dtrace' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld'
> '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo'
> '--with-llvm' 'LLVM_CONFIG=/usr/bin/llvm-config-6.0'
> 'CLANG=/usr/bin/clang-6.0' '--with-systemd' '--with-selinux'
> 'MKDIR_P=/bin/mkdir -p' 'TAR=/bin/tar' 'CFLAGS=-g -O2
> -fstack-protector-strong -Wformat -Werror=format-security
> -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-z,relro -Wl,-z,now' '--with-gssapi'
> '--with-ldap' '--with-includes=/usr/include/mit-krb5'
> '--with-libs=/usr/lib/mit-krb5'
> '--with-libs=/usr/lib/x86_64-linux-gnu/mit-krb5'
> 'build_alias=x86_64-linux-gnu' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'
> 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security'
> CC = gcc
> CPPFLAGS = -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE
> -I/usr/include/libxml2 -I/usr/include/mit-krb5
> CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security
> -fno-omit-frame-pointer
> CFLAGS_SL = -fPIC
> LDFLAGS = -Wl,-z,relro -Wl,-z,now -L/usr/lib/llvm-6.0/lib
> -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed
> LDFLAGS_EX =
> LDFLAGS_SL =
> LIBS = -lpgcommon -lpgport -lpthread -lselinux -lxslt -lxml2 -lpam -lssl
> -lcrypto -lgssapi_krb5 -lz -ledit -lrt -lcrypt -ldl -lm
> VERSION = PostgreSQL 11.8 (Debian 11.8-1.pgdg90+1)
>
>
and do you have a file "postgres.h" in /usr/include/postgresql/11/server
directory?

**Comment by asharabu** [comment]
Hi,

When I installed postgresql-server-dev-11 using the below command. It seems the issue fixed. Thanks

apt install postgresql-server-dev-11

**Comment by okbob** [comment]
čt 28. 5. 2020 v 14:20 odesílatel asharabu <notifications@github.com>
napsal:

> Hi,
>
> When I installed postgresql-server-dev-11 using the below command. It
> seems the issue fixed. Thanks
>
> apt install postgresql-server-dev-11
>

great

Pavel

**Comment by technillogue** [comment]
Hi, @asharabu , could you share your Dockerfile?
