### ISSUE TITLE
Segmentation fault on plpgsql_check_function

### ISSUE THREAD

**Issue by andruche** [okbob/plpgsql_check#62]
```
tmpdb=# select version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 11.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
(1 row)


tmpdb=# create extension plpgsql_check;
CREATE EXTENSION


tmpdb=# select extname, extversion from pg_extension ;
    extname    | extversion
---------------+------------
 plpgsql       | 1.0
 plpgsql_check | 1.9
(2 rows)


tmpdb=# 
create or replace function f() returns void as $$
declare
  r record;
begin
  r := json_populate_record(r, '[]');
end;
$$ language plpgsql;
CREATE FUNCTION


tmpdb=# select plpgsql_check_function('f()');
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Comment by okbob** [comment]
Hi

po 1. 6. 2020 v 15:10 odesílatel Andrey Chernyakov <notifications@github.com>
napsal:

> tmpdb=# select version();
>                                                  version
> ---------------------------------------------------------------------------------------------------------
>  PostgreSQL 11.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11), 64-bit
> (1 row)
>
>
> tmpdb=# create extension plpgsql_check;
> CREATE EXTENSION
>
>
> tmpdb=# select extname, extversion from pg_extension ;
>     extname    | extversion
> ---------------+------------
>  plpgsql       | 1.0
>  plpgsql_check | 1.9
> (2 rows)
>
>
> tmpdb=#
> create or replace function f() returns void as $$
> declare
>   r record;
> begin
>   r := json_populate_record(r, '[]');
> end;
> $$ language plpgsql;
> CREATE FUNCTION
>
>
> tmpdb=# select plpgsql_check_function('f()');
> server closed the connection unexpectedly
>         This probably means the server terminated abnormally
>         before or while processing the request.
> The connection to the server was lost. Attempting reset: Failed.
>
>
please, can you recheck build. I build plpgsql_check from scratch, and I
cannot to repeat your example.

postgres=# select version();
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                 version
                               │
╞══════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ PostgreSQL 11.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 10.1.1
20200507 (Red Hat 10.1.1-1), 64-bit │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(1 row)

postgres=# select plpgsql_check_function('f()');
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                            plpgsql_check_function
                                   │
╞══════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ error:42804:5:assignment:function does not return composite type, is not
possible to identify composite type │
│ Context: at assignment to variable "r" declared on line 3
                                   │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(2 rows)

I see different issue - the error message is bad, but I don't see the crash

Pavel

**Comment by okbob** [comment]
I fixed some uninitialized memory there. Please, check master or release 1.10.1

**Comment by andruche** [comment]
Hi

> I fixed some uninitialized memory there. Please, check master or release 1.10.1

I checked plpgsql_check 1.10.1 with postgresql 11.8 and 12.3.
Now segmentation fault is gone.
Thanks a lot for so quick resolve! )

**Comment by okbob** [comment]
pá 5. 6. 2020 v 14:18 odesílatel Andrey Chernyakov <notifications@github.com>
napsal:

> Hi
>
> I fixed some uninitialized memory there. Please, check master or release
> 1.10.1
>
> I checked plpgsql_check 1.10.1 with postgresql 11.8 and 12.3.
> Now segmentation fault is gone.
> Thanks a lot for so quick resolve! )
>

Thank you for report

Pavel
