### ISSUE TITLE
disable "routine marked as..." performance warnings on void functions

### ISSUE THREAD

**Issue by bakter80** [okbob/plpgsql_check#65]
Is there any reason to show a "routine is marked as VOLATILE, should be STABLE." when the function RETURNS void?

**Comment by okbob** [comment]
út 14. 7. 2020 v 18:02 odesílatel bakter80 <notifications@github.com>
napsal:

> Is there any reason to show a "routine is marked as VOLATILE, should be
> STABLE." when the function RETURNS void?
>

What I know, no. Stable is running in R/W mode like VOLATILE - so the speed
of runtime will be same.

Regards

Pavel

**Comment by bakter80** [comment]
I think it's better to remove volatility warnings for void functions.
And do so (according to the documentation "Any function with side-effects must be labeled VOLATILE") with functions contains RAISE EXCEPTION.

**Comment by okbob** [comment]
st 15. 7. 2020 v 9:55 odesílatel bakter80 <notifications@github.com> napsal:

> I think it's better to remove volatility warnings for void functions.
> And do so (according to the documentation "Any function with side-effects
> must be labeled VOLATILE") with functions contains RAISE EXCEPTION.
>

should be done by last commit

Regards

Pavel

**Comment by bakter80** [comment]
It seems to work.
Thanks
