### ISSUE TITLE
Unnecessary performance warning when hiden cast text <=> character varying

### ISSUE THREAD

**Issue by kattunga** [okbob/plpgsql_check#66]
Hi,

Postgresql treats "character varying/varchar" as "text" as same type for index searches.
I made several test and same index are always used no matter which of this 2 types you use

where field=value:text
where field=value:character varying

In my functions I usually mix this 2 types because character varying let me specify a size for formatting grids in function that return tables and my table data types are usually text.

I think that reporting this hidden cast as a performance issue is wrong.

Is there any way to disable only this performance warning?

**Comment by okbob** [comment]
pá 17. 7. 2020 v 6:07 odesílatel Christian Pradelli <
notifications@github.com> napsal:

> Hi,
>
> Postgresql treats "character varying/varchar" as "text" as same type for
> index searches.
> I made several test and same index are always used no matter which of this
> 2 types you use
>
> where field=value:text
> where field=value:character varying
>
> In my procedures I usually mix this 2 types because character varying let
> me specify a size for formatting grids in function that return tables and
> my table data types are usually text.
>
> I think that reporting this hidden cast as a performance issue is wrong.
>
> Is there any way to disable only this performance warning?
>
It is not possible on plpgsql_level - but it is possible on SQL level. You
can filter this warning by its own filter in WHERE clause.

I thought about it aboutremove this warning. But I think it is better to
hold it. It is type inconsistency. It hasn't a real performance issue, but
it is something strange when you compare text and varchar.

Regards

Pavel

**Comment by okbob** [comment]
pá 17. 7. 2020 v 6:07 odesílatel Christian Pradelli <
notifications@github.com> napsal:

> Hi,
>
> Postgresql treats "character varying/varchar" as "text" as same type for
> index searches.
> I made several test and same index are always used no matter which of this
> 2 types you use
>
> where field=value:text
> where field=value:character varying
>
> In my procedures I usually mix this 2 types because character varying let
> me specify a size for formatting grids in function that return tables and
> my table data types are usually text.
>
> I think that reporting this hidden cast as a performance issue is wrong.
>
> Is there any way to disable only this performance warning?
>
Can you send me an example. I try to reproduce this issue, and I cannot.
Maybe it depends on version plpgsql_check and version of Postgres.

**Comment by kattunga** [comment]
Hi,
I'm sorry was my mistake, field was character, not character varying and this is an issue performance.
Everything works as expected.

Regards

**Comment by okbob** [comment]
pá 17. 7. 2020 v 23:13 odesílatel Christian Pradelli <
notifications@github.com> napsal:

> Hi,
> I'm sorry was my mistake, field was character, not character varying and
> this is an issue performance.
> Everything works as expected.
>
super :), thank you for informing me

Regards

Pavel
