### ISSUE TITLE
ERROR:  could not find function "plpgsql_check_function_tb_name" in file "/usr/lib/postgresql/10/lib/plpgsql_check.so"

### ISSUE THREAD

**Issue by bradleyf** [okbob/plpgsql_check#68]
Release 1.11.3:

This happens on CREATE EXTENSION plpgsql_check.  Please advise.

**Comment by okbob** [comment]
st 22. 7. 2020 v 23:26 odesílatel Bradley Feldman <notifications@github.com>
napsal:

> Release 1.11.3:
>
> This happens on CREATE EXTENSION plpgsql_check. Please advise.
>
This function is relatively old in plpgsql_check. Can you write more info
about your installation?

maybe you have some older library of plpgsql_check?

**Comment by okbob** [comment]
any progress?
