### ISSUE TITLE
plpgsql_check support for Postgres procedures

### ISSUE THREAD

**Issue by aleszeleny** [okbob/plpgsql_check#72]
Would it be possible to add support also for procedures?
I'll appreciate it even if there will be only some functionality supported for procedures compared to function.

**Comment by okbob** [comment]
Procedures are supported by default:
<pre>
postgres=# create procedure xx(a int)
postgres-# as $$
postgres$# declare b int;
postgres$# begin
postgres$#   b := a;
postgres$# end;
postgres$# $$ language plpgsql;
CREATE PROCEDURE
postgres=# select * from plpgsql_check_function('xx');
┌───────────────────────────────────────────────────────┐
│                plpgsql_check_function                 │
╞═══════════════════════════════════════════════════════╡
│ warning extra:00000:2:DECLARE:never read variable "b" │
└───────────────────────────────────────────────────────┘
(1 row)
</pre>

What I know all features of procedures are supported.

**Comment by aleszeleny** [comment]
Sorry, it was my typo in proceure name while trying to use plpgsql_check on procedure fisrt time :-)
