### ISSUE TITLE
ERROR: unexpected number of parameters, you should to update extension SQL state: XX000

### ISSUE THREAD

**Issue by bradleyf** [okbob/plpgsql_check#75]
In attempting to downgrade back to a sane release of plpgsql_check I get the message in the title line.   

I always:

DROP EXTENSION plpgsql_check:
CREATE  EXTENSION plpgsql_check;

Makes no difference.

**Comment by okbob** [comment]
There is inconsistency between plpgsql_check--1.xxx.sql  and content of used plpgsql_check.so file. Probably you don't downgrade plpgsql_check.so. The report message is related to internal check inside library if number of arguments are correct.

**Comment by bradleyf** [comment]
Apparently, either Make Install isn't replacing these files, or DROP EXTENSION plpgsql_check: isn't cleaning up these files.  I'm using Postgres 12

**Comment by okbob** [comment]
pá 9. 10. 2020 v 18:26 odesílatel Bradley Feldman <notifications@github.com>
napsal:

> Apparently, either Make Install isn't replacing these files, or DROP
> EXTENSION plpgsql_check: isn't cleaning up these files. I'm using Postgres
> 12
>

DROP EXTENSION doesn't clean the library. It just cleans PostgreSQL system
catalogue - but all others are without change. make install should to
replace files. It should work - but maybe you have more lib dirs.

you should to do

SQL: DROP EXTENSION

git checkout xxx - good version
make
sudo make install --- ATTENTION - with sudo, or su - there can be different
configuration - maybe there are other bin directories

SQL CREATE EXTENSION ...

please check if

pg_config --libdir

and

sudo pg_config --libdir

returns same directory

maybe you have more "pg_config" related to different versions,
configurations, ... in your computer

**Comment by okbob** [comment]
any progress?
