### ISSUE TITLE
README.md on a tracing facility

### ISSUE THREAD

**Issue by pluzanov** [okbob/plpgsql_check#76]
It seems that there is a typo in a README.md file:
"Tracing is enabled by setting plpgsql_check.tracing to on." 

May be plpgsql_check.tracer ?

Thank you for very useful extension.

**Comment by okbob** [comment]
true, thank you for report. Should be fixed now.

**Comment by pluzanov** [comment]
And one more question. For enabling tracing I need set two parameters with similar names: enable_tracer and tracer. It is not very obvious why one parameter is not enough.

**Comment by okbob** [comment]
pá 23. 10. 2020 v 18:17 odesílatel Pavel <notifications@github.com> napsal:

> And one more question. For enabling tracing I need set two parameters with
> similar names: enable_tracer and tracer. It is not very obvious why one
> parameter is not enough.
>
It is for security reasons - a non power user can see sensitive data inside
security definer functions with tracing. So there should be two levels of
enabling - one is by superuser, that should be sure so there are not
security definer functions or there are not sensitive data on the server.
And second level just for user, that can enable or disable tracing when it
is required, but he doesn't need superuser rights.

**Comment by pluzanov** [comment]
Thank you for explanations.

**Comment by okbob** [comment]
ook :)
