### ISSUE TITLE
fatal error during make installcheck on Windows

### ISSUE THREAD

**Issue by pashagolub** [okbob/plpgsql_check#77]
Hello Pavel,

was testing `plgpsql_check` on Windows with the latest `PostgreSQL 13`, and I can reproduce the fatal error in two ways:
- `make installcheck`
- `psql \i sql/plpgsql_check_active.sql`

Both produce fatal errors, but on different statements, which is suspecous and make me think about memory corruption.

Output for `make installcheck`:
```bash
$ make installcheck
C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/lib/POSTGR~1/pgxs/src/MAKEFI~1/../../src/test/regress/pg_regress --inputdir=./ --bindir='C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/bin'    --dbname=pl_regression --dbname=contrib_regression plpgsql_check_passive plpgsql_check_active plpgsql_check_active-13 plpgsql_check_passive-13
(using postmaster on localhost, default port)
============== dropping database "contrib_regression" ==============
NOTICE:  database "contrib_regression" does not exist, skipping
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test plpgsql_check_passive        ... ok          138 ms
test plpgsql_check_active         ... FAILED (test process exited with exit code 2)      462 ms
test plpgsql_check_active-13      ... ok          197 ms
test plpgsql_check_passive-13     ... ok          114 ms

======================
 1 of 4 tests failed.
======================

The differences that caused some tests to fail can be viewed in the
file "C:/Users/pasha/Code/postgresql-windows-packaging/msys64/src/plpgsql_check/regression.diffs".  A copy of the test summary that you see
above is saved in the file "C:/Users/pasha/Code/postgresql-windows-packaging/msys64/src/plpgsql_check/regression.out".

make: *** [C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/lib/POSTGR~1/pgxs/src/MAKEFI~1/pgxs.mk:420: installcheck] Error 1
```

Postgres log:
```bash
....
2020-10-26 17:39:42.867 GMT [8012] CONTEXT:  PL/pgSQL function fx_flow()
2020-10-26 17:39:42.867 GMT [8012] STATEMENT:  select fx_flow();
2020-10-26 17:39:43.010 GMT [13648] LOG:  server process (PID 8012) was terminated by exception 0xC00000FF
2020-10-26 17:39:43.010 GMT [13648] DETAIL:  Failed process was running: drop function fx_flow();
2020-10-26 17:39:43.010 GMT [13648] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2020-10-26 17:39:43.010 GMT [13648] LOG:  terminating any other active server processes
2020-10-26 17:39:43.011 GMT [22396] WARNING:  terminating connection because of crash of another server process
2020-10-26 17:39:43.011 GMT [22396] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-10-26 17:39:43.011 GMT [22396] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-10-26 17:39:43.024 GMT [13648] LOG:  all server processes terminated; reinitializing
2020-10-26 17:39:43.062 GMT [7872] LOG:  database system was interrupted; last known up at 2020-10-26 17:39:42 GMT
2020-10-26 17:39:43.385 GMT [7872] LOG:  database system was not properly shut down; automatic recovery in progress
2020-10-26 17:39:43.390 GMT [7872] LOG:  redo starts at 0/16FE900
2020-10-26 17:39:43.433 GMT [7872] LOG:  invalid record length at 0/17A1138: wanted 24, got 0
2020-10-26 17:39:43.433 GMT [7872] LOG:  redo done at 0/17A10D0
2020-10-26 17:39:43.543 GMT [13648] LOG:  database system is ready to accept connections
....
```

Output for `psql \i sql/plpgsql_check_active.sql`:
```bash
...
DROP FUNCTION
CREATE FUNCTION
 functionid | lineno | statement | sqlstate | message | detail | hint | level | position | query | context
------------+--------+-----------+----------+---------+--------+------+-------+----------+-------+---------
(0 rows)


CREATE FUNCTION
 functionid | lineno | statement | sqlstate |     message      | detail | hint |     level     | position | query | context
------------+--------+-----------+----------+------------------+--------+------+---------------+----------+-------+---------
 fx_flow    |     12 | RETURN    | 00000    | unreachable code |        |      | warning extra |          |       |
(1 row)


psql:sql/plpgsql_check_active.sql:1876: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
psql:sql/plpgsql_check_active.sql:1876: fatal: connection to server was lost
```
I can help you debug this error if it's specific to Windows. 

Thanks in advance

**Comment by okbob** [comment]
Hi Pavlo 

It is probably specific to Windows.  Now, I tested it against all supported releases (with 9.5-14) without any problem. I never run regress tests on windows, so this issue can be long time there. I don't use windows. Postgres 13 has possibility to log stack trace. Is some information there? Can you isolate code from plpgsql_check_active.sql, that crash Postgres? 

Probably the most important line from log 
<code>
DETAIL:  Failed process was running: drop function fx_flow();
</code>

It fails (probably) outside plpgsql_check - so maybe plpgsql_check breaks plpgsql memory or doesn't free some references.

It strange, because bad DROP FUNCTION fx_flow() is probably useless and it try to drop already dropped function.

**Comment by pashagolub** [comment]
No problem. I can help you, I hope :) 

Can you please point me to how to enable stack trace? Yeah, I'll try to split sql into pieces and see if it still causing any errors.

**Comment by okbob** [comment]
út 27. 10. 2020 v 11:07 odesílatel Pavlo Golub <notifications@github.com>
napsal:

> No problem. I can help you, I hope :)
>
> Can you please point me to how to enable stack trace? Yeah, I'll try to
> split sql into pieces and see if it still causing any errors.
>

I though

set backtrace_functions = 'int4div';

but It doesn't help with segfaults :(. So you can try to attach postgres
from Visual Studio to take stack trace.

Pavel

**Comment by pashagolub** [comment]
Ahoj,

I've rechecked regression against the official build and found there is no any issue. 

Seems I have corrupted PostgreSQL binaries on my test environment. Have no idea if I want to debug it, but it's for sure not a `plpgsql_check` bug.

Sorry for inconveniences. Great job!

```bash
$ make installcheck
C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/lib/POSTGR~1/pgxs/src/MAKEFI~1/../../src/test/regress/pg_regress --inputdir=./ --bindir='C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/bin'    --dbname=pl_regression --dbname=contrib_regression plpgsql_check_passive plpgsql_check_active plpgsql_check_active-13 plpgsql_check_passive-13
(using postmaster on localhost, default port)
============== dropping database "contrib_regression" ==============
NOTICE:  database "contrib_regression" does not exist, skipping
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test plpgsql_check_passive        ... ok          140 ms
test plpgsql_check_active         ... ok          461 ms
test plpgsql_check_active-13      ... ok          145 ms
test plpgsql_check_passive-13     ... ok          107 ms

=====================
 All 4 tests passed.
=====================
```

**Comment by okbob** [comment]
út 27. 10. 2020 v 12:29 odesílatel Pavlo Golub <notifications@github.com>
napsal:

> Ahoj,
>
> I've rechecked regression against the official build and found there is no
> any issue.
>
> Seems I have corrupted PostgreSQL binaries on my test environment. Have no
> idea if I want to debug it, but it's for sure not a plpgsql_check bug.
>
It is hard to say where the problem is. I know that PostgreSQL extensions
on windows are very sensitive to build environment that should be almost
the same like Postgres binaries - more windows are more sensitive on
allocation, releasing memory in libraries - but if it is working, then it
is probably not this issue.


> Sorry for inconveniences. Great job!
>
> $ make installcheck
> C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/lib/POSTGR~1/pgxs/src/MAKEFI~1/../../src/test/regress/pg_regress --inputdir=./ --bindir='C:/Users/pasha/Code/POSTGR~1/msys64/usr/local/pg64/bin'    --dbname=pl_regression --dbname=contrib_regression plpgsql_check_passive plpgsql_check_active plpgsql_check_active-13 plpgsql_check_passive-13
> (using postmaster on localhost, default port)
> ============== dropping database "contrib_regression" ==============
> NOTICE:  database "contrib_regression" does not exist, skipping
> DROP DATABASE
> ============== creating database "contrib_regression" ==============
> CREATE DATABASE
> ALTER DATABASE
> ============== running regression test queries        ==============test plpgsql_check_passive        ... ok          140 mstest plpgsql_check_active         ... ok          461 mstest plpgsql_check_active-13      ... ok          145 mstest plpgsql_check_passive-13     ... ok          107 ms
>
> =====================
>  All 4 tests passed.
> =====================
>
>
No problem :), I thank you so you did a regress tests of plpgsql_check on
windows. It was first time probably :)

**Comment by pashagolub** [comment]
If you are interested, I can try to implement the Github Actions workflow for automatic testing

**Comment by okbob** [comment]
út 27. 10. 2020 v 13:26 odesílatel Pavlo Golub <notifications@github.com>
napsal:

> If you are interested, I can try to implement the Github Actions workflow
> for automatic testing
>
If you can automate tests under windows, it can be really really great!

I use automated tests, but these tests are running on Debian.
