### ISSUE TITLE
No warning when testing a trigger function that has no return in it

### ISSUE THREAD

**Issue by marco44** [okbob/plpgsql_check#78]
"normal" functions have the warning though.

```
create function demo () returns int language plpgsql as
$$
begin
end
$$
;
select * from plpgsql_check_function('demo()');
                   plpgsql_check_function                   
------------------------------------------------------------
 error:2F005:control reached end of function without RETURN
```
against:
```
create function demo_trigger () returns trigger language plpgsql as
$$
begin
end
$$
;
select * from plpgsql_check_function('demo_trigger()',relid:='role_employeearticlecache');
 plpgsql_check_function 
------------------------
```

Am I missing something ?

Regards

**Comment by okbob** [comment]
st 28. 10. 2020 v 15:58 odesílatel Marc Cousin <notifications@github.com>
napsal:

> "normal" functions have the warning though.
>
> create function demo () returns int language plpgsql as
> $$
> begin
> end
> $$
> ;
> select * from plpgsql_check_function('demo()');
>                    plpgsql_check_function
> ------------------------------------------------------------
>  error:2F005:control reached end of function without RETURN
>
> against:
>
> create function demo_trigger () returns trigger language plpgsql as
> $$
> begin
> end
> $$
> ;
> select * from plpgsql_check_function('demo_trigger()',relid:='role_employeearticlecache');
>  plpgsql_check_function
> ------------------------
>
> Am I missing something ?
>

It looks like plpgsql_check bug. I'll check it.

Regards

Pavel

Regards

**Comment by okbob** [comment]
Should be fixed now by last commit. Please check.

**Comment by marco44** [comment]
Yes, solved. Thanks a lot !

**Comment by okbob** [comment]
čt 29. 10. 2020 v 10:07 odesílatel Marc Cousin <notifications@github.com>
napsal:

> Yes, solved. Thanks a lot !
>

Thank you for report

Pavel
