### ISSUE TITLE
Possibility to add queryid to the profiler?

### ISSUE THREAD

**Issue by rjuju** [okbob/plpgsql_check#79]
Hello,

I needed a plpgsql profiler recently, and plpgsql_check works like a charm, so thanks a lot for writing it!

I'm now looking at ways to get more information, and I'm wondering if it could be possible to also store the queryid, when possible, along the other profiler information.  This could help to match slow statements in plpgsql functions to pg_stat_statements entries, and/or any other extension that provides metrics based on that queryid.

I'm unfortunately not very familiar with plpgsql code, so I'm not sure if it's possible to get that info reliably.

For the record here's a short snippet that I used in `plpgsql_check_profiler_stmt_end` to quickly check if I could at least retrieve the queryid in the standard cases:

```
	PLpgSQL_expr *expr = NULL;

	switch(stmt->cmd_type)
	{
		case PLPGSQL_STMT_PERFORM:
			expr = ((PLpgSQL_stmt_perform *) stmt)->expr;
			break;
		case PLPGSQL_STMT_ASSIGN:
			expr = ((PLpgSQL_stmt_assign *) stmt)->expr;
			break;
		case PLPGSQL_STMT_RETURN:
			expr = ((PLpgSQL_stmt_return *) stmt)->expr;
			break;
		case PLPGSQL_STMT_EXIT:
			expr = ((PLpgSQL_stmt_exit *) stmt)->cond;
			break;
[...]
		default:
			break;
	}

	if (expr)
	{
		SPIPlanPtr ptr  = expr->plan;
		ListCell *lc;

		foreach(lc, SPI_plan_get_plan_sources(ptr))
		{
			CachedPlanSource *source = (CachedPlanSource *) lfirst(lc);
			ListCell *lc2;

			foreach(lc2, source->query_list)
			{
				Query *q = lfirst_node(Query, lc2);

				elog(WARNING, "%d - %zu: %s", stmt->stmtid, q->queryId, source->query_string);
			}
		}
	}
```

It seems to work quite well, but I'm not sure if it's possible to get multiple plansources and/or multiple query for a single plpgsql expr, and if yes what to do in that case.

Do you have any opinion on that?

**Comment by okbob** [comment]
čt 5. 11. 2020 v 10:17 odesílatel Julien Rouhaud <notifications@github.com>
napsal:

> Hello,
>
> I needed a plpgsql profiler recently, and plpgsql_check works like a
> charm, so thanks a lot for writing it!
>
> I'm now looking at ways to get more information, and I'm wondering if it
> could be possible to also store the queryid, when possible, along the other
> profiler information. This could help to match slow statements in plpgsql
> functions to pg_stat_statements entries, and/or any other extension that
> provides metrics based on that queryid.
>
> I'm unfortunately not very familiar with plpgsql code, so I'm not sure if
> it's possible to get that info reliably.
>
> For the record here's a short snippet that I used in
> plpgsql_check_profiler_stmt_end to quickly check if I could at least
> retrieve the queryid in the standard cases:
>
> 	PLpgSQL_expr *expr = NULL;
>
> 	switch(stmt->cmd_type)
> 	{
> 		case PLPGSQL_STMT_PERFORM:
> 			expr = ((PLpgSQL_stmt_perform *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_ASSIGN:
> 			expr = ((PLpgSQL_stmt_assign *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_RETURN:
> 			expr = ((PLpgSQL_stmt_return *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_EXIT:
> 			expr = ((PLpgSQL_stmt_exit *) stmt)->cond;
> 			break;
> [...]
> 		default:
> 			break;
> 	}
>
> 	if (expr)
> 	{
> 		SPIPlanPtr ptr  = expr->plan;
> 		ListCell *lc;
>
> 		foreach(lc, SPI_plan_get_plan_sources(ptr))
> 		{
> 			CachedPlanSource *source = (CachedPlanSource *) lfirst(lc);
> 			ListCell *lc2;
>
> 			foreach(lc2, source->query_list)
> 			{
> 				Query *q = lfirst_node(Query, lc2);
>
> 				elog(WARNING, "%d - %zu: %s", stmt->stmtid, q->queryId, source->query_string);
> 			}
> 		}
> 	}
>
> It seems to work quite well, but I'm not sure if it's possible to get
> multiple plansources and/or multiple query for a single plpgsql expr, and
> if yes what to do in that case.
>
> Do you have any opinion on that?
>
It can be good enhancing. I will look at it.

**Comment by rjuju** [comment]
Thanks!  For the record I'm willing to write a patch for that, if the approach if you're ok with the approach I mentioned (probably using the 1st Query of the 1st CachedPlanSource).

**Comment by okbob** [comment]
čt 5. 11. 2020 v 10:46 odesílatel Julien Rouhaud <notifications@github.com>
napsal:

> Thanks! For the record I'm willing to write a patch for that, if the
> approach if you're ok with the approach I mentioned (probably using the 1st
> Query of the 1st CachedPlanSource).
>

ok, if you can, send a pull request. Important question is a performance,
now profiler has minimal performance impact, so queryId should not be
calculated repeatedly.

**Comment by okbob** [comment]
čt 5. 11. 2020 v 10:17 odesílatel Julien Rouhaud <notifications@github.com>
napsal:

> Hello,
>
> I needed a plpgsql profiler recently, and plpgsql_check works like a
> charm, so thanks a lot for writing it!
>
> I'm now looking at ways to get more information, and I'm wondering if it
> could be possible to also store the queryid, when possible, along the other
> profiler information. This could help to match slow statements in plpgsql
> functions to pg_stat_statements entries, and/or any other extension that
> provides metrics based on that queryid.
>
> I'm unfortunately not very familiar with plpgsql code, so I'm not sure if
> it's possible to get that info reliably.
>
> For the record here's a short snippet that I used in
> plpgsql_check_profiler_stmt_end to quickly check if I could at least
> retrieve the queryid in the standard cases:
>
> 	PLpgSQL_expr *expr = NULL;
>
> 	switch(stmt->cmd_type)
> 	{
> 		case PLPGSQL_STMT_PERFORM:
> 			expr = ((PLpgSQL_stmt_perform *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_ASSIGN:
> 			expr = ((PLpgSQL_stmt_assign *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_RETURN:
> 			expr = ((PLpgSQL_stmt_return *) stmt)->expr;
> 			break;
> 		case PLPGSQL_STMT_EXIT:
> 			expr = ((PLpgSQL_stmt_exit *) stmt)->cond;
> 			break;
> [...]
> 		default:
> 			break;
> 	}
>
> 	if (expr)
> 	{
> 		SPIPlanPtr ptr  = expr->plan;
> 		ListCell *lc;
>
> 		foreach(lc, SPI_plan_get_plan_sources(ptr))
> 		{
> 			CachedPlanSource *source = (CachedPlanSource *) lfirst(lc);
> 			ListCell *lc2;
>
> 			foreach(lc2, source->query_list)
> 			{
> 				Query *q = lfirst_node(Query, lc2);
>
> 				elog(WARNING, "%d - %zu: %s", stmt->stmtid, q->queryId, source->query_string);
> 			}
> 		}
> 	}
>
> It seems to work quite well, but I'm not sure if it's possible to get
> multiple plansources and/or multiple query for a single plpgsql expr, and
> if yes what to do in that case.
>
I am sure so EXECUTE can generate multiple plans, and if you use rules,
then you can get multiple plans too.

Regards

Pavel

**Comment by rjuju** [comment]
Done in PR https://github.com/okbob/plpgsql_check/pull/80, closing the issue.
