### ISSUE TITLE
Expose MAX_SHARED_CHUNKS for user configuration

### ISSUE THREAD

**Issue by rjuju** [okbob/plpgsql_check#81]
Hello again,

I want to use the profiler at work, and my use case is to have the extension loaded in shared_preload_libraries, and activate the profiler on a per-function(s) basis, with all functions involved not being very large.

As a consequence, it'd be useful to limit the memory usage of the profiler which can be done exposing MAX_SHARED_CHUNKS as a GUC.

I'd like to write a patch for that if you're interested in that change.  If yes, would you like to expose the parameter as-is (documenting that each chunk can store up to 30 statements), using another approach for the GUC (maybe only exposing the wanted maximal number of lines, internally divided by STATEMENTS_PER_CHUNK), or exposing both parameters?

**Comment by okbob** [comment]
It is hard question - I am not sure, but probably the best is size of shared memory - line is too small unit. So one GUC can be "plpgsql_check"."profiler_shared_buffers", and second "plpgsql_check"."profiler_statements_per_function" ? STATEMENTS_PER_CHUNK should be good enough most common number of statements in functions. In ideal case, the one function has one chunk. But if this number is too high, then lot of allocated shared buffers will be unused. 

What do you think?

**Comment by okbob** [comment]
I afraid if we use lines as basic metric, then some people uses very big numbers (for their safety), and there can be problem with overallocation of shared memory, and Postgres doesn't start. So safer (and I am not sure if it is better, but I am sure so it is safer), is using memory as base with documentation how much memory is necessary for thousands lines.

**Comment by rjuju** [comment]
Yes that's a hard question.  I'm afraid that exposing the shared_buffers size will make it hard to configure for users, so I'm still thinking on how to make it less error-prone.

It's still possible to define the GUC with a minimal possible value, so that no one ask for a few dozens statements maximum or something like that.  We could alternatively ask for a number of lines, but exposing it in 1k lines unit maybe?

I'm also worried about profiler_statements_per_function.  It could be misunderstood by users as a hard limit, thus setting it way too high.  I don't think there are a lot of use cases where this number should be changed, as it's quite unlikely to have an enormous amount of functions that only contains a few statements.

**Comment by okbob** [comment]
> Yes that's a hard question. I'm afraid that exposing the shared_buffers size will make it hard to configure for users, so I'm still thinking on how to make it less error-prone.
> 
> It's still possible to define the GUC with a minimal possible value, so that no one ask for a few dozens statements maximum or something like that. We could alternatively ask for a number of lines, but exposing it in 1k lines unit maybe?

It is really hard, because there is important number of statements, not number of lines. So I afraid so any metric based on lines is problematic too. Maybe we thinking too much about it. Any user friendly design has some advantage and disadvantage - so what about GUC MAX_SHARED_CHUNKS without masking any complexity. This has a advantage so user should to understand all impacts and possible dependencies. This is config value - and it can be changed any time without problems later if it doesn't work well.

??


> 
> I'm also worried about profiler_statements_per_function. It could be misunderstood by users as a hard limit, thus setting it way too high. I don't think there are a lot of use cases where this number should be changed, as it's quite unlikely to have an enormous amount of functions that only contains a few statements.

ok, so it will be better to hide this argument against users,

**Comment by rjuju** [comment]
Agreed!  I'll try to be as clear as possible on the documentation.

**Comment by okbob** [comment]
I released 1.14.0

**Comment by rjuju** [comment]
Oh great, thanks a lot!
