### ISSUE TITLE
functions with char parameters do not work with profiler

### ISSUE THREAD

**Issue by sean-bennett112** [okbob/plpgsql_check#84]
I'm fairly new to using `plpgsql_check`, so it's possible I'm missing something, but I can't seem to get the profiler to work with character types on Postgres 11.

Here's a minimal working example I came up with:

```sql
\dx
                        List of installed extensions
     Name      | Version |   Schema   |             Description              
---------------+---------+------------+--------------------------------------
 plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
 plpgsql_check | 1.15    | public     | extended check for plpgsql functions
(2 rows)

set plpgsql_check.profiler = on;
SET
drop function if exists public.f1;
psql:temp.sql:5: NOTICE:  function public.f1() does not exist, skipping
DROP FUNCTION
create or replace function public.f1(thing char(1))
    returns int
    language plpgsql
as $function$
    begin
        return 1;
    end
$function$;
CREATE FUNCTION
select * from plpgsql_profiler_function_statements_tb('f1');
 stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     
--------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
      0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
      1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
(2 rows)

select f1('h');
psql:temp.sql:17: ERROR:  broken statement map - cannot to find statement on line: 3
CONTEXT:  PL/pgSQL function f1(character) line 3 at RETURN
select * from plpgsql_profiler_function_statements_tb('f1');
 stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     
--------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
      0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
      1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
(2 rows)
```

I'm running in Docker with the following:

Dockerfile:

```docker
FROM postgres:11

RUN apt-get update \
    # && apt-cache showpkg postgresql-$PG_MAJOR-pgtap \
    && apt-get install -y --no-install-recommends \
    postgresql-$PG_MAJOR-plpgsql-check \
    && rm -rf /var/lib/apt/lists/*
```

contents of init directory passed into docker(these get run at initial container startup:

```bash
#!/usr/bin/env bash

set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
	create extension if not exists "plpgsql_check";
	alter system set shared_preload_libraries = plpgsql, plpgsql_check;
SQL
```

`text` and `varchar` types also produce similar behavior.

It does appear to work correctly if I switch things out for Postgres 12, which unfortunately isn't an option for me.

**Comment by okbob** [comment]
Hi

pá 29. 1. 2021 v 3:08 odesílatel Sean Bennett <notifications@github.com>
napsal:

> I'm fairly new to using plpgsql_check, so it's possible I'm missing
> something, but I can't seem to get the profiler to work with character
> types on Postgres 11.
>
> Here's a minimal working example I came up with:
>
> \dx
>                         List of installed extensions
>      Name      | Version |   Schema   |             Description              ---------------+---------+------------+--------------------------------------
>  plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
>  plpgsql_check | 1.15    | public     | extended check for plpgsql functions
> (2 rows)
> set plpgsql_check.profiler = on;SETdrop function if exists public.f1;
> psql:temp.sql:5: NOTICE:  function public.f1() does not exist, skippingDROP FUNCTIONcreate or replace function public.f1(thing char(1))
>     returns int
>     language plpgsqlas $function$
>     begin
>         return 1;
>     end
> $function$;
> CREATE FUNCTIONselect * from plpgsql_profiler_function_statements_tb('f1');
>  stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     --------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
>       0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
>       1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
> (2 rows)
> select f1('h');
> psql:temp.sql:17: ERROR:  broken statement map - cannot to find statement on line: 3
> CONTEXT:  PL/pgSQL function f1(character) line 3 at RETURNselect * from plpgsql_profiler_function_statements_tb('f1');
>  stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     --------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
>       0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
>       1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
> (2 rows)
>
> I'm running in Docker with the following:
>
> Dockerfile:
>
> FROM postgres:11
>
> RUN apt-get update \
>     # && apt-cache showpkg postgresql-$PG_MAJOR-pgtap \
>     && apt-get install -y --no-install-recommends \
>     postgresql-$PG_MAJOR-plpgsql-check \
>     && rm -rf /var/lib/apt/lists/*
>
> contents of init directory passed into docker(these get run at initial
> container startup:
>
> #!/usr/bin/env bash
> set -euo pipefail
>
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL	create extension if not exists "plpgsql_check";	alter system set shared_preload_libraries = plpgsql, plpgsql_check;SQL
>
> text and varchar types also produce similar behavior.
>
> It does appear to work correctly if I switch things out for Postgres 12,
> which unfortunately isn't an option for me.
>
Yes, I am able to reproduce this issue. I'll try to fix it.

Regards

Pavel

**Comment by okbob** [comment]
Hi

pá 29. 1. 2021 v 3:08 odesílatel Sean Bennett <notifications@github.com>
napsal:

> I'm fairly new to using plpgsql_check, so it's possible I'm missing
> something, but I can't seem to get the profiler to work with character
> types on Postgres 11.
>
> Here's a minimal working example I came up with:
>
> \dx
>                         List of installed extensions
>      Name      | Version |   Schema   |             Description              ---------------+---------+------------+--------------------------------------
>  plpgsql       | 1.0     | pg_catalog | PL/pgSQL procedural language
>  plpgsql_check | 1.15    | public     | extended check for plpgsql functions
> (2 rows)
> set plpgsql_check.profiler = on;SETdrop function if exists public.f1;
> psql:temp.sql:5: NOTICE:  function public.f1() does not exist, skippingDROP FUNCTIONcreate or replace function public.f1(thing char(1))
>     returns int
>     language plpgsqlas $function$
>     begin
>         return 1;
>     end
> $function$;
> CREATE FUNCTIONselect * from plpgsql_profiler_function_statements_tb('f1');
>  stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     --------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
>       0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
>       1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
> (2 rows)
> select f1('h');
> psql:temp.sql:17: ERROR:  broken statement map - cannot to find statement on line: 3
> CONTEXT:  PL/pgSQL function f1(character) line 3 at RETURNselect * from plpgsql_profiler_function_statements_tb('f1');
>  stmtid | parent_stmtid | parent_note | block_num | lineno | queryid | exec_stmts | total_time | avg_time | max_time | processed_rows |    stmtname     --------+---------------+-------------+-----------+--------+---------+------------+------------+----------+----------+----------------+-----------------
>       0 |               |             |         1 |      2 |         |          0 |          0 |          |        0 |              0 | statement block
>       1 |             0 | body        |         1 |      3 |         |          0 |          0 |          |        0 |              0 | RETURN
> (2 rows)
>
> I'm running in Docker with the following:
>
> Dockerfile:
>
> FROM postgres:11
>
> RUN apt-get update \
>     # && apt-cache showpkg postgresql-$PG_MAJOR-pgtap \
>     && apt-get install -y --no-install-recommends \
>     postgresql-$PG_MAJOR-plpgsql-check \
>     && rm -rf /var/lib/apt/lists/*
>
> contents of init directory passed into docker(these get run at initial
> container startup:
>
> #!/usr/bin/env bash
> set -euo pipefail
>
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL	create extension if not exists "plpgsql_check";	alter system set shared_preload_libraries = plpgsql, plpgsql_check;SQL
>
> text and varchar types also produce similar behavior.
>
> It does appear to work correctly if I switch things out for Postgres 12,
> which unfortunately isn't an option for me.
>
This issue should be fixed. Unfortunately, there was more than one issue
and the profiler's code was pretty tired and dirty, so I had to rewrite
important parts of this code.

Please, check and test.

Regards

Pavel

**Comment by sean-bennett112** [comment]
Sorry for the late reply, I just wanted to confirm that this is indeed working for me now. Thanks very much!

**Comment by okbob** [comment]
pá 12. 3. 2021 v 16:12 odesílatel Sean Bennett ***@***.***>
napsal:

> Sorry for the late reply, I just wanted to confirm that this is indeed
> working for me now. Thanks very much!
>
Thank you for checking :)

Pavel
