### ISSUE TITLE
issues compiling on latest postgres source code

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#86]
trying to compile this extension with latest code version from  https://github.com/postgres/postgres.git  I get an error

src/parse_name.c:207:11: error: too few arguments to function ‘FuncnameGetCandidates’
   clist = FuncnameGetCandidates(names, -1, NIL, false, false, true);

either I made a mistake or it might be related to postgres commit e56bce5d43 on 10. Jun. 2021 where this function has changed, but my knowledge in C does not go further to be able to tell the impact.

**Comment by rjuju** [comment]
Hi,

I hit the same problem in some internal CI today.  I just submitted https://github.com/okbob/plpgsql_check/pull/87 which hopefully should fix it.

**Comment by rjuju** [comment]
FTR @okbob just merge the PR.
