### ISSUE TITLE
1.17.0 fails to build against v14

### ISSUE THREAD

**Issue by devrimgunduz** [okbob/plpgsql_check#89]
Hi @okbob ,

1.17.0 fails to build against v14. Can you please take a look? Thanks! Devrim

> gcc -Wextra -g -fPIC -I/usr/pgsql-14/lib/pgxs/src/makefiles/../../src/pl/plpgsql/src -Wall -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/report.o src/report.c
> src/parse_name.c: In function 'plpgsql_check_parse_name_or_signature':
> src/parse_name.c:207:25: error: too many arguments to function 'FuncnameGetCandidates'
>   207 |                 clist = FuncnameGetCandidates(names, -1, NIL, false, false,
>       |                         ^~~~~~~~~~~~~~~~~~~~~
> In file included from src/parse_name.c:14:
> /usr/pgsql-14/include/server/catalog/namespace.h:98:26: note: declared here
>    98 | extern FuncCandidateList FuncnameGetCandidates(List *names,
>       |                          ^~~~~~~~~~~~~~~~~~~~~
> make[1]: *** [<builtin>: src/parse_name.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> src/profiler.c: In function 'profiler_get_expr':
> src/profiler.c:1912:9: warning: enumeration value 'PLPGSQL_STMT_SET' not handled in switch [-Wswitch]
>  1912 |         switch(stmt->cmd_type)
>       |         ^~~~~~
> make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/plpgsql_check/master/plpgsql_check-1.17.0'
> error: Bad exit status from /var/tmp/rpm-tmp.w1hycT (%build)
> 
> 
>

**Comment by okbob** [comment]
po 21. 6. 2021 v 20:44 odesílatel Devrim Gündüz ***@***.***>
napsal:

> Hi @okbob <https://github.com/okbob> ,
>
> 1.17.0 fails to build against v14. Can you please take a look? Thanks!
> Devrim
>
This commit e56bce5d43789cce95d099554ae9593ada92b3b7 breaks API. So
plpgsql_check is compileable against the master branch, but it is broken
against the last beta :-/

The commit f171e62dba659597c387e357d9f1e14f69032bc0 should to fix it.

Pavel




gcc -Wextra -g -fPIC

**Comment by rjuju** [comment]
Is that really necessary to go into that level of support?  Postgres 14 is still in beta so I don't think it's critical to get the latest version of all extensions old the oldest beta when there's an API break between two betas, especially 3 days before the new beta.

**Comment by okbob** [comment]
út 22. 6. 2021 v 5:03 odesílatel Julien Rouhaud ***@***.***>
napsal:

> Is that really necessary to go into that level of support? Postgres 14 is
> still in beta so I don't think it's critical to get the latest version of
> all extensions old the oldest beta when there's an API break between two
> betas, especially 3 days before the new beta.
>

I'll remove this change after the new beta - this is a provisory solution.

Pavel

**Comment by rjuju** [comment]
Ah I see, it makes sense.  Thanks!

**Comment by okbob** [comment]
I removed this workaround - master branch and plpgsql_check 1.17.1 are compile-able against Postgres 14 beta2
