### ISSUE TITLE
check SQL functions

### ISSUE THREAD

**Issue by fvannee** [okbob/plpgsql_check#91]
Functions that are defined as SQL rather than PLPGSQL have stricter checks on creation in Postgres (if `check_function_bodies` is true). Most errors are caught there. However, afterwards, it is still possible that the function becomes invalid. For example, it is possible that the table that it references in SELECT gets dropped or changed afterwards. It would be great if this extension could also check SQL functions, or possibly if you are aware of any other ways to check if a SQL function is still valid after creation. The only way I can come up with without the extension is to generate the exact `CREATE OR REPLACE FUNCTION` statement for that specific function and check if it still runs, but that actually modifies it
Is this an idea for addition, or might you know a better way of achieving this without extension?

**Comment by okbob** [comment]
út 24. 8. 2021 v 16:15 odesílatel Floris van Nee ***@***.***>
napsal:

> Functions that are defined as SQL rather than PLPGSQL have stricter checks
> on creation in Postgres (if check_function_bodies is true). Most errors
> are caught there. However, afterwards, it is still possible that the
> function becomes invalid. For example, it is possible that the table that
> it references in SELECT gets dropped or changed afterwards. It would be
> great if this extension could also check SQL functions, or possibly if you
> are aware of any other ways to check if a SQL function is still valid after
> creation. The only way I can come up with without the extension is to
> generate the exact CREATE OR REPLACE FUNCTION statement for that specific
> function and check if it still runs, but that actually modifies it
> Is this an idea for addition, or might you know a better way of achieving
> this without extension?
>
Using CREATE OR REPLACE FUNCTION is the most easy solution, and I think it
will be only a few percent slower than a specialized extension.
Theoretically anybody can write an extension that uses the
`prepare_sql_fn_parse_info` function. Maybe it can be a new function
plpgsql_check_sql_function for plpgsql_check. I am not sure how much work
it needs, probably not too much. I can write it, but now I am working on a
different topic. I welcome the pull request.

Postgres 14 will support new syntax for SQL functions - with a little bit
different implementation. When you use this new function - probably the
functions should be transferred manually to this new syntax, the inner
dependency will be protected.

When I did some basic and fast research, I found a topic on stackoverflow,
that can be good enough

https://stackoverflow.com/questions/54422768/how-to-re-check-an-sql-function-created-with-check-function-bodies-false

The C code can do +/- same thing - call sql validator function , so maybe C
extensions is not necessary

fmgr_sql_validator

**Comment by fvannee** [comment]
`fmgr_sql_validator` is wonderful. I did not know that this was accessible from SQL already. Thanks!
