### ISSUE TITLE
it seems a recent commit on postgres master branch breaks compilation

### ISSUE THREAD

**Issue by neiaberau** [okbob/plpgsql_check#93]
Hi,

not high importance for me, just to let you know, 
compiling with latest Postgres Code from master, I  get this error:

...
src/check_expr.c: In function ‘ExprGetQuery’:
src/check_expr.c:338:20: error: ‘union ValUnion’ has no member named ‘type’
         if (ac->val.type == T_String)
                    ^
make: *** [<builtin>: src/check_expr.o] Error 1
The command '/bin/sh -c cd /home/postgres/plpgsql_ch

I assume this has been triggered by this commit on postgres master 
639a86e36a 2021-09-09 08:36:53 +0200 Peter Eisentraut Remove Value node struct

 (just guessing  based on commit message, but I might be wrong or made an error  myself, as I cannot code c, but it complied  for me until recently)

**Comment by okbob** [comment]
so 11. 9. 2021 v 10:24 odesílatel neiaberau ***@***.***>
napsal:

> Hi,
>
> not high importance for me, just to let you know,
> compiling with latest Postgres Code from master, I get this error:
>
> ...
> src/check_expr.c: In function ‘ExprGetQuery’:
> src/check_expr.c:338:20: error: ‘union ValUnion’ has no member named ‘type’
> if (ac->val.type == T_String)
> ^
> make: *** [: src/check_expr.o] Error 1
> The command '/bin/sh -c cd /home/postgres/plpgsql_ch
>
> I assume this has been triggered by this commit on postgres master
> 639a86e36a 2021-09-09 08:36:53 +0200 Peter Eisentraut Remove Value node
> struct
>
> (just guessing based on commit message, but I might be wrong or made an
> error myself, as I cannot code c, but it complied for me until recently)
>

yes, I expected it

I'll fix it

**Comment by okbob** [comment]
Should be fixed now by last commit

**Comment by neiaberau** [comment]
thanks a lot

**Comment by okbob** [comment]
Thank you for report

ne 12. 9. 2021 v 11:33 odesílatel neiaberau ***@***.***>
napsal:
