### ISSUE TITLE
plpgsql_coverage_{branches, statements}(name) statistics with raise exceptions

### ISSUE THREAD

**Issue by clbouvier** [okbob/plpgsql_check#99]
Hello,

I am using pgtap a lot for testing my plpgsql code.

I have discovered plpgsql_check can return interesting statistics about unit tests coverage ; however I hit some weird results.

the problem is raising when I am using the next pattern functions:

```plpgsql
CREATE FUNCTION inner_function(val text)
RETURNS void
AS
$$
DECLARE
    inc int not null := 0;
BEGIN
    if val is not null then
            inc := inc + 1;
        else
            raise not_null_violation;
        end if;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION wrapping_exception(val text)
RETURNS void
AS
$$
DECLARE
    inc int not null := 0;
BEGIN
    begin
        perform inner_function(val);
    exception
        when not_null_violation then
            raise exception 'expected violation "%".', val
            using errcode = '99998';
    end;
END;
$$ LANGUAGE plpgsql;
```

Calling the wrapping_function with an argument which does not hit any raise exception statement is fine:
```
select wrapping_function('a');
select * from plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                       0.5
(1 ligne)

```
Now with NULL argument:

```
select wrapping_function(NULL);
ERROR:  not_null_violation
...
select * from plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                       0.5
(1 ligne)

```
If we unit tests with the both arguments, we might naturally think that the branches coverage should be 1. because the both branches are scanned.

As mentioned in the README if the function fails then the profile is not updated but that might give erroneous statistics about branches coverages.

I don't know if there is any fix with this use-case (if statement with raise exception).

**Comment by okbob** [comment]
út 30. 11. 2021 v 7:30 odesílatel clbouvier ***@***.***>
napsal:

> Hello,
>
> I am using pgtap a lot for testing my plpgsql code.
>
> I have discovered plpgsql_check can return interesting statistics about
> unit tests coverage ; however I hit some weird results.
>
> the problem is raising when I am using the next pattern functions:
>
> CREATE FUNCTION inner_function(val text)
> RETURNS voidAS
> $$
> DECLARE
>     inc int not null := 0;BEGIN
>     if val is not null then
>             inc := inc + 1;
>         else
>             raise not_null_violation;
>         end if;
> END;
> $$ LANGUAGE plpgsql;
> CREATE FUNCTION wrapping_exception(val text)
> RETURNS voidAS
> $$
> DECLARE
>     inc int not null := 0;BEGIN
>     begin
>         perform inner_function(val);
>     exception
>         when not_null_violation then
>             raise exception 'expected violation "%".', val
>             using errcode = '99998';
>     end;
> END;
> $$ LANGUAGE plpgsql;
>
> Calling the wrapping_function with an argument which does not hit any
> raise exception statement is fine:
>
> select wrapping_function('a');
> select * from plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches
> ---------------------------
>                        0.5
> (1 ligne)
>
>
> Now with NULL argument:
>
> select wrapping_function(NULL);
> ERROR:  not_null_violation
> ...
> select * from plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches
> ---------------------------
>                        0.5
> (1 ligne)
>
>
> If we unit tests with the both arguments, we might naturally think that
> the branches coverage should be 1. because the both branches are scanned.
>
> As mentioned in the README if the function fails then the profile is not
> updated but that might give erroneous statistics about branches coverages.
>
> I don't know if there is any fix with this use-case (if statement with
> raise exception).
>
There are two issues:

1. I am not able to detect wanted (expected) and unwanted exceptions before
an exception. I increment the exec counter on the statement end, and in
this case, the statement end is not executed due to the exception.

2. After an exception plpgsql doesn't call my hooks where I save a profile
to shared memory.

I don't see any possible fix of this issue. The impossibility to save a
profile to shared memory is a principal problem.

**Comment by okbob** [comment]
I found an solution. It is relatively hardcore trick, but it works. 

please, test 2.1.0 release

**Comment by clbouvier** [comment]
> I found an solution. It is relatively hardcore trick, but it works.
> 
> please, test 2.1.0 release
Thanks,

Quickly, I have tested on macos 11.6 with postgreSQL 13.5.
I have some trouble with no logs with the last version: 2.1
I have preloaded the extension:

shared_preload_libraries = 'pg_stat_statements,plpgsql,plpgsql_check'
 
 The instance cannot run (probably is crashing).
 The instance is running fine without preloading.
 
 The  version 2.0.6 is fine with the same configuration with plpgsql_check in shared_preload_libraries.
 
 The extension (with the different versions) was installed with pgxnclient.
 
 I will report more details when I have tested with other configurations.

**Comment by clbouvier** [comment]
> > I found an solution. It is relatively hardcore trick, but it works.
> > please, test 2.1.0 release
> 
> Thanks,
> 
> Quickly, I have tested on macos 11.6 with postgreSQL 13.5. I have some trouble with no logs with the last version: 2.1 I have preloaded the extension:
> 
> shared_preload_libraries = 'pg_stat_statements,plpgsql,plpgsql_check'
> 
> The instance cannot run (probably is crashing). The instance is running fine without preloading.

Please, discard that I said (sorry for the noise). I need to check more ;  apparently the instance is taking time to launch itself.

I will report back any news.

**Comment by okbob** [comment]
čt 30. 12. 2021 v 9:07 odesílatel clbouvier ***@***.***>
napsal:

> I found an solution. It is relatively hardcore trick, but it works.
>
> please, test 2.1.0 release
> Thanks,
>
> Quickly, I have tested on macos 11.6 with postgreSQL 13.5.
> I have some trouble with no logs with the last version: 2.1
> I have preloaded the extension:
>
> shared_preload_libraries = 'pg_stat_statements,plpgsql,plpgsql_check'
>
> The instance cannot run (probably is crashing).
> The instance is running fine without preloading.
>
> The version 2.0.6 is fine with the same configuration with plpgsql_check
> in shared_preload_libraries.
>
> The extension (with the different versions) was installed with pgxnclient.
>
> I will report more details when I have tested with other configurations.
>
There was a catalog change. You need to first drop previous version by DROP
EXTENSION command.

**Comment by clbouvier** [comment]
Hi,

I did use the both functions of the PR: inner_function, wrapping_exception.
I checked with an ubuntu LTS 20.04 and postgresl 12:

```sql
coverage_2.1=>  SELECT * FROM pg_extension;
  oid  |    extname    | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------------+----------+--------------+----------------+------------+-----------+--------------
 13413 | plpgsql       |       10 |           11 | f              | 1.0        |           | 
 16387 | plpgsql_check |       10 |         2200 | f              | 2.1        |           | 
(2 rows)

coverage_2.1=> set plpgsql_check.profiler to on;

coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
 plpgsql_coverage_branches 
---------------------------
                         1
(1 row)

coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                         0
(1 row)
```
I have already checked but the branch coverage gives always 1 to any without IF/THEN/ELSE dance. The result is a little bit curious because we could expect that the couple BEGIN/EXCEPTION should count as a branch and in this case before running the function count as 0.
I have seen that with trigger function.

```sql
SELECT wrapping_exception('a');
 wrapping_exception 
--------------------
 
(1 row)

coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                       0.5
(1 row)

coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
 plpgsql_coverage_branches 
---------------------------
                         1
(1 row)
```
In this case wrapping_exception should gives 0.5 because only one path in the BEGIN/EXCEPTION is run.

```sql
overage_2.1=> SELECT wrapping_exception(NULL);
ERROR:  expected violation "<NULL>".
CONTEXT:  PL/pgSQL function wrapping_exception(text) line 9 at RAISE
coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                         1
(1 row)
```

This is nice because that is working !

```sql
coverage_2.1=> SELECT lineno, stmt_lineno, cmds_on_row, exec_stmts, exec_stmts_err, processed_rows, source FROM plpgsql_profiler_function_tb('inner_function');
 lineno | stmt_lineno | cmds_on_row | exec_stmts | exec_stmts_err | processed_rows |                source                 
--------+-------------+-------------+------------+----------------+----------------+---------------------------------------
      1 |             |             |            |                |                | 
      2 |             |             |            |                |                | DECLARE
      3 |             |             |            |                |                |     inc int not null := 0;
      4 |           4 |           1 |          2 |              0 | {0}            | BEGIN
      5 |           5 |           1 |          2 |              0 | {0}            |     if val is not null then
      6 |           6 |           1 |          1 |              0 | {0}            |             inc := inc + 1;
      7 |             |             |            |                |                |         else
      8 |           8 |           1 |          1 |              1 | {0}            |             raise not_null_violation;
      9 |             |             |            |                |                |         end if;
     10 |             |             |            |                |                | END;
(10 rows)

coverage_2.1=> SELECT lineno, stmt_lineno, cmds_on_row, exec_stmts, exec_stmts_err, processed_rows, source FROM plpgsql_profiler_function_tb('wrapping_exception');
 lineno | stmt_lineno | cmds_on_row | exec_stmts | exec_stmts_err | processed_rows |                           source                           
--------+-------------+-------------+------------+----------------+----------------+------------------------------------------------------------
      1 |             |             |            |                |                | 
      2 |             |             |            |                |                | DECLARE
      3 |             |             |            |                |                |     inc int not null := 0;
      4 |           4 |           1 |          2 |              0 | {1}            | BEGIN
      5 |           5 |           1 |          2 |              0 | {1}            |     begin
      6 |           6 |           1 |          2 |              1 | {1}            |         perform inner_function(val);
      7 |             |             |            |                |                |     exception
      8 |             |             |            |                |                |         when not_null_violation then
      9 |           9 |           1 |          1 |              1 | {0}            |             raise exception 'expected violation "%".', val
     10 |             |             |            |                |                |             using errcode = '99998';
     11 |             |             |            |                |                |     end;
     12 |             |             |            |                |                | END;
(12 rows)
```
I wonder what does mean the column processed_rows because I have thought that the lines of inner_function was processed because this function is used in the function wrapping_exception.

Moreover I noticed with the passive mode that overriding the configuration of shared_preload_libraries = 'plpgsql,plpgsql_check' , the postgreSQL instance does not start.
I have the same behaviour on macos and on ubuntu LTS 20.04 (on ubuntu it is a pristine setup).

I will give it more check with a battery of pgTap unit tests ; but currently I am loosing the metrics when the session of a test is done.

Excellent. Thanks a lot!

This is one of last missing piece (in my opinion of course) to have a complete set for code testing framework in postgreSQL.
There was piggly for coverage of course but I find your extension on this side super attractive.

**Comment by okbob** [comment]
čt 30. 12. 2021 v 12:37 odesílatel clbouvier ***@***.***>
napsal:

> Hi,
>
> I did use the both functions of the PR: inner_function, wrapping_exception.
> I checked with an ubuntu LTS 20.04 and postgresl 12:
>
> coverage_2.1=>  SELECT * FROM pg_extension;
>   oid  |    extname    | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition -------+---------------+----------+--------------+----------------+------------+-----------+--------------
>  13413 | plpgsql       |       10 |           11 | f              | 1.0        |           |
>  16387 | plpgsql_check |       10 |         2200 | f              | 2.1        |           |
> (2 rows)
> coverage_2.1=> set plpgsql_check.profiler to on;
> coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
>  plpgsql_coverage_branches ---------------------------
>                          1
> (1 row)
> coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                          0
> (1 row)
>
> I have already checked but the branch coverage gives always 1 to any
> without IF/THEN/ELSE dance. The result is a little bit curious because we
> could expect that the couple BEGIN/EXCEPTION should count as a branch and
> in this case before running the function count as 0.
>
This is just not supported yet probably. I am not an expert on coverage
metric - I did it just as an optional feature to profiler. So there can be
more bugs.

Can you prepare some test cases? Probably I can fix it, but it is just an
area where I do not have enough knowledge.


> I have seen that with trigger function.
>
> SELECT wrapping_exception('a');
>  wrapping_exception --------------------
>
> (1 row)
> coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                        0.5
> (1 row)
> coverage_2.1=> SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
>  plpgsql_coverage_branches ---------------------------
>                          1
> (1 row)
>
> In this case wrapping_exception should gives 0.5 because only one path in
> the BEGIN/EXCEPTION is run.
>
> overage_2.1=> SELECT wrapping_exception(NULL);
> ERROR:  expected violation "<NULL>".
> CONTEXT:  PL/pgSQL function wrapping_exception(text) line 9 at RAISEcoverage_2.1=> SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                          1
> (1 row)
>
> This is nice because that is working !
>
> coverage_2.1=> SELECT lineno, stmt_lineno, cmds_on_row, exec_stmts, exec_stmts_err, processed_rows, source FROM plpgsql_profiler_function_tb('inner_function');
>  lineno | stmt_lineno | cmds_on_row | exec_stmts | exec_stmts_err | processed_rows |                source                 --------+-------------+-------------+------------+----------------+----------------+---------------------------------------
>       1 |             |             |            |                |                |
>       2 |             |             |            |                |                | DECLARE
>       3 |             |             |            |                |                |     inc int not null := 0;
>       4 |           4 |           1 |          2 |              0 | {0}            | BEGIN
>       5 |           5 |           1 |          2 |              0 | {0}            |     if val is not null then
>       6 |           6 |           1 |          1 |              0 | {0}            |             inc := inc + 1;
>       7 |             |             |            |                |                |         else
>       8 |           8 |           1 |          1 |              1 | {0}            |             raise not_null_violation;
>       9 |             |             |            |                |                |         end if;
>      10 |             |             |            |                |                | END;
> (10 rows)
> coverage_2.1=> SELECT lineno, stmt_lineno, cmds_on_row, exec_stmts, exec_stmts_err, processed_rows, source FROM plpgsql_profiler_function_tb('wrapping_exception');
>  lineno | stmt_lineno | cmds_on_row | exec_stmts | exec_stmts_err | processed_rows |                           source                           --------+-------------+-------------+------------+----------------+----------------+------------------------------------------------------------
>       1 |             |             |            |                |                |
>       2 |             |             |            |                |                | DECLARE
>       3 |             |             |            |                |                |     inc int not null := 0;
>       4 |           4 |           1 |          2 |              0 | {1}            | BEGIN
>       5 |           5 |           1 |          2 |              0 | {1}            |     begin
>       6 |           6 |           1 |          2 |              1 | {1}            |         perform inner_function(val);
>       7 |             |             |            |                |                |     exception
>       8 |             |             |            |                |                |         when not_null_violation then
>       9 |           9 |           1 |          1 |              1 | {0}            |             raise exception 'expected violation "%".', val
>      10 |             |             |            |                |                |             using errcode = '99998';
>      11 |             |             |            |                |                |     end;
>      12 |             |             |            |                |                | END;
> (12 rows)
>
> I wonder what does mean the column processed_rows because I have thought
> that the lines of inner_function was processed because this function is
> used in the function wrapping_exception.
>
It makes sense just for SQL commands - it returns the number of rows
returned by SQL engine. This is calculated by SQL engine.

> Moreover I noticed with the passive mode that overriding the configuration
> of shared_preload_libraries = 'plpgsql,plpgsql_check' , the postgreSQL
> instance does not start.
>
This can be a bug. I'll check it. I had to use relatively complex hacks, so
it is possible, so I broke it.


> I have the same behaviour on macos and on ubuntu LTS 20.04 (on ubuntu it
> is a pristine setup).
>
> I will give it more check with a battery of pgTap unit tests ; but
> currently I am loosing the metrics when the session of a test is done.
>
> Excellent. Thanks a lot!
>
> This is one of last missing piece (in my opinion of course) to have a
> complete set for code testing framework in postgreSQL.
> There was piggly for coverage of course but I find your extension on this
> side super attractive.
>
It is not too bad for a hobby project.  Thank you

**Comment by okbob** [comment]
all mentioned issues should be fixed in 2.1.1 - please, check

**Comment by clbouvier** [comment]
Happy new year and sorry not being able to check before.

Thanks !

> please, check

I have upgraded to the new version 2.1.1
The postgreSQL instances have started with shared_preload_libraries = 'plpgsql,plpgsql_check' in postgresql.conf
(whatever the system ubuntu LTS 20.04 and macos)
so it is fine on this side. Thank you.

I have checked the statistics about braches coverage:

```sql
coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
 plpgsql_coverage_branches 
---------------------------
                         0
(1 row)

coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                         0
(1 row)

coverage_2.1=# SELECT wrapping_exception('a');
 wrapping_exception 
--------------------
 
(1 row)

coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                       0.5
(1 row)

coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
 plpgsql_coverage_branches 
---------------------------
                       0.5
(1 row)

coverage_2.1=# SELECT wrapping_exception(NULL);
ERROR:  expected violation "<NULL>".
CONTEXT:  PL/pgSQL function wrapping_exception(text) line 9 at RAISE

coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
 plpgsql_coverage_branches 
---------------------------
                         1
(1 row)
```

Yes, it is fine.
I will give more tests but that sounds good for me.

>This is just not supported yet probably. I am not an expert on coverage
metric - I did it just as an optional feature to profiler. So there can be
more bugs.

> Can you prepare some test cases? Probably I can fix it, but it is just an
area where I do not have enough knowledge.

I am not an expert too :-) . But for sure I can prepare some test case.

I will check the next commit commit that you have done. I suppose that you have already done the test cases with the previous cases...Anyway I can check a little bit more and if I find something weird, I can submit a test case.

However I don't know if I would have the same pace than you ! (you are fast).

I have a question:

When I check the version of the extension with pg_extension, I found the version 2.1 (fine).
When I have upgraded to 2.1.1, the version keep the same numbers. Do you consider more than minor for the project?

Thank you.

**Comment by okbob** [comment]
čt 6. 1. 2022 v 7:14 odesílatel clbouvier ***@***.***> napsal:

> Happy new year and sorry not being able to check before.
>
> Thanks !
>
> please, check
>
> I have upgraded to the new version 2.1.1
> The postgreSQL instances have started with shared_preload_libraries =
> 'plpgsql,plpgsql_check' in postgresql.conf
> (whatever the system ubuntu LTS 20.04 and macos)
> so it is fine on this side. Thank you.
>
> I have checked the statistics about braches coverage:
>
> coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
>  plpgsql_coverage_branches ---------------------------
>                          0
> (1 row)
> coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                          0
> (1 row)
> coverage_2.1=# SELECT wrapping_exception('a');
>  wrapping_exception --------------------
>
> (1 row)
> coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                        0.5
> (1 row)
> coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('wrapping_exception');
>  plpgsql_coverage_branches ---------------------------
>                        0.5
> (1 row)
> coverage_2.1=# SELECT wrapping_exception(NULL);
> ERROR:  expected violation "<NULL>".
> CONTEXT:  PL/pgSQL function wrapping_exception(text) line 9 at RAISE
> coverage_2.1=# SELECT * FROM plpgsql_coverage_branches('inner_function');
>  plpgsql_coverage_branches ---------------------------
>                          1
> (1 row)
>
> Yes, it is fine.
> I will give more tests but that sounds good for me.
>
> This is just not supported yet probably. I am not an expert on coverage
> metric - I did it just as an optional feature to profiler. So there can be
> more bugs.
>
> Can you prepare some test cases? Probably I can fix it, but it is just an
> area where I do not have enough knowledge.
>
> I am not an expert too :-) . But for sure I can prepare some test case.
>
> I will check the next commit commit that you have done. I suppose that you
> have already done the test cases with the previous cases...Anyway I can
> check a little bit more and if I find something weird, I can submit a test
> case.
>
> However I don't know if I would have the same pace than you ! (you are
> fast).
>
> I have a question:
>
> When I check the version of the extension with pg_extension, I found the
> version 2.1 (fine).
> When I have upgraded to 2.1.1, the version keep the same numbers. Do you
> consider more than minor for the project?
>
The plpgsql_check doesn't support upgrade scripts now - so any change on
SQL level means DROP EXTENSION and CREATE EXTENSION. And this can cause
some issues when people have some higher code over plpgsql_check.

So I try to reduce increment version numbers visible from SQL level.
Usually I increment the first two numbers only when there is a change of
API (or where there is important functionality change). Last number is the
bugfix release number, and this number is not (in case of plpgsql_check)
visible from SQL level. For bugfix release you just need to copy the
library to the correct place and restart Postgres (when you use shared
preload libraries) or just to use a new connection to Postgres.

It is a little bit dirty, but it reduces the number of files and the
necessity to create empty update scripts.

Regards

Pavel
